# DateTimes

### Introduction

Deciding which features should be included and focused on in our linear model is an important skill of any data scientist.  As we saw previously, if we include features which are too collinear, we will improperly measure the coefficients related to our collinear features.  In addition, feature selection and prioritizing features with feature importance will help us to understand which features to devote our attention to in terms of feature engineering and domain understanding.  Finally, limiting the number of features in our model, and identifying the most crucial features in our model will make our models, and their insights more understandable.

### Working with AirBnb

For this lesson, we'll work with [AirBnb listings in Berlin](https://www.kaggle.com/brittabettendorf/berlin-airbnb-data).

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mhan1/Data-Science/master/listings_summary.csv')

In [2]:
df.shape

(22552, 96)

As we can see, our dataset as 22,500 rows and close to 100 features.  Our goal is to predict the price.

In [3]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

Some of these columns include data that we do not know how to handle - mainly textual data and images.  A lot of this data is simply not in the correct format.  Let's take a look.

In [4]:
pd.set_option('display.max_rows',100)

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,22552.0,1.571560e+07,8.552069e+06,2.015000e+03,8.065954e+06,1.686638e+07,2.258393e+07,2.986735e+07
scrape_id,22552.0,2.018111e+13,4.812607e+00,2.018111e+13,2.018111e+13,2.018111e+13,2.018111e+13,2.018111e+13
thumbnail_url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
medium_url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
xl_picture_url,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,22552.0,5.403355e+07,5.816290e+07,2.217000e+03,9.240002e+06,3.126711e+07,8.067518e+07,2.245081e+08
host_acceptance_rate,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_listings_count,22526.0,2.330685e+00,1.994782e+01,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.676000e+03
host_total_listings_count,22526.0,2.330685e+00,1.994782e+01,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.676000e+03
latitude,22552.0,5.250982e+01,3.082546e-02,5.234580e+01,5.248906e+01,5.250908e+01,5.253267e+01,5.265167e+01
longitude,22552.0,1.340611e+01,5.796365e-02,1.310356e+01,1.337541e+01,1.341678e+01,1.343926e+01,1.375764e+01
accommodates,22552.0,2.637460e+00,1.510548e+00,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.600000e+01
bathrooms,22520.0,1.092695e+00,3.298943e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,8.500000e+00
bedrooms,22534.0,1.161134e+00,6.461559e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.200000e+01
beds,22512.0,1.620558e+00,1.174840e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.200000e+01
square_feet,446.0,4.654013e+02,5.034919e+02,0.000000e+00,0.000000e+00,4.035000e+02,7.075000e+02,4.639000e+03
guests_included,22552.0,1.332121e+00,8.350343e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.600000e+01
minimum_nights,22552.0,7.157059e+00,4.066507e+01,1.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,5.000000e+03
maximum_nights,22552.0,1.030505e+05,9.640519e+06,1.000000e+00,2.000000e+01,1.124000e+03,1.125000e+03,1.000000e+09
availability_30,22552.0,4.944173e+00,8.677395e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00,3.000000e+01
availability_60,22552.0,1.114664e+01,1.752237e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,6.000000e+01
availability_90,22552.0,2.001610e+01,2.834914e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.600000e+01,9.000000e+01
availability_365,22552.0,7.985283e+01,1.193682e+02,0.000000e+00,0.000000e+00,4.000000e+00,1.290000e+02,3.650000e+02
number_of_reviews,22552.0,1.784068e+01,3.676962e+01,0.000000e+00,1.000000e+00,5.000000e+00,1.600000e+01,4.980000e+02
review_scores_rating,18163.0,9.441386e+01,7.639644e+00,2.000000e+01,9.200000e+01,9.700000e+01,1.000000e+02,1.000000e+02
review_scores_accuracy,18138.0,9.663965e+00,7.400390e-01,2.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_cleanliness,18141.0,9.324955e+00,1.031996e+00,2.000000e+00,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_checkin,18120.0,9.713521e+00,7.046199e-01,2.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_communication,18134.0,9.730672e+00,6.866140e-01,2.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_location,18121.0,9.505491e+00,7.621606e-01,2.000000e+00,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
review_scores_value,18117.0,9.411106e+00,8.414916e-01,2.000000e+00,9.000000e+00,1.000000e+01,1.000000e+01,1.000000e+01
jurisdiction_names,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
calculated_host_listings_count,22552.0,1.918233e+00,3.667257e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.500000e+01
reviews_per_month,18638.0,1.135525e+00,1.507082e+00,1.000000e-02,1.800000e-01,5.400000e-01,1.500000e+00,3.667000e+01

A lot of the data is listed as objects, which is really a catch all.

In [6]:
df.dtypes

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
summary                              object
space                                object
description                          object
experiences_offered                  object
neighborhood_overview                object
notes                                object
transit                              object
access                               object
interaction                          object
house_rules                          object
thumbnail_url                       float64
medium_url                          float64
picture_url                          object
xl_picture_url                      float64
host_id                               int64
host_url                             object
host_name                            object
host_since                           object
host_location                        object
host_about                           object
host_response_time                   object
host_response_rate                   object
host_acceptance_rate                float64
host_is_superhost                    object
host_thumbnail_url                   object
host_picture_url                     object
host_neighbourhood                   object
host_listings_count                 float64
host_total_listings_count           float64
host_verifications                   object
host_has_profile_pic                 object
host_identity_verified               object
street                               object
neighbourhood                        object
neighbourhood_cleansed               object
neighbourhood_group_cleansed         object
city                                 object
state                                object
zipcode                              object
market                               object
smart_location                       object
country_code                         object
country                              object
latitude                            float64
longitude                           float64
is_location_exact                    object
property_type                        object
room_type                            object
accommodates                          int64
bathrooms                           float64
bedrooms                            float64
beds                                float64
bed_type                             object
amenities                            object
square_feet                         float64
price                                object
weekly_price                         object
monthly_price                        object
security_deposit                     object
cleaning_fee                         object
guests_included                       int64
extra_people                         object
minimum_nights                        int64
maximum_nights                        int64
calendar_updated                     object
has_availability                     object
availability_30                       int64
availability_60                       int64
availability_90                       int64
availability_365                      int64
calendar_last_scraped                object
number_of_reviews                     int64
first_review                         object
last_review                          object
review_scores_rating                float64
review_scores_accuracy              float64
review_scores_cleanliness           float64
review_scores_checkin               float64
review_scores_communication         float64
review_scores_location              float64
review_scores_value                 float64
requires_license                     object
license                              object
jurisdiction_names                  float64
instant_bookable                     object
is_business_travel_ready             object
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64
dtype: object

In [7]:
df.dtypes[10:15]

notes          object
transit        object
access         object
interaction    object
house_rules    object
dtype: object

In [8]:
def find_object_features(df):
    return list(df.dtypes[df.dtypes == 'object'].index)

In [9]:
find_object_features(df)

['listing_url',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'picture_url',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'is_location_exact',
 'property_type',
 'room_type',
 'bed_type',
 'amenities',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'extra_people',
 'calendar_updated',
 'has_availability',
 'calendar_last_scraped',
 'first_review',
 'last_review',
 'requires_license',
 'license',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification']

In [10]:
df.dtypes[df.dtypes == 'object']

listing_url                         object
last_scraped                        object
name                                object
summary                             object
space                               object
description                         object
experiences_offered                 object
neighborhood_overview               object
notes                               object
transit                             object
access                              object
interaction                         object
house_rules                         object
picture_url                         object
host_url                            object
host_name                           object
host_since                          object
host_location                       object
host_about                          object
host_response_time                  object
host_response_rate                  object
host_is_superhost                   object
host_thumbnail_url                  object
host_picture_url                    object
host_neighbourhood                  object
host_verifications                  object
host_has_profile_pic                object
host_identity_verified              object
street                              object
neighbourhood                       object
neighbourhood_cleansed              object
neighbourhood_group_cleansed        object
city                                object
state                               object
zipcode                             object
market                              object
smart_location                      object
country_code                        object
country                             object
is_location_exact                   object
property_type                       object
room_type                           object
bed_type                            object
amenities                           object
price                               object
weekly_price                        object
monthly_price                       object
security_deposit                    object
cleaning_fee                        object
extra_people                        object
calendar_updated                    object
has_availability                    object
calendar_last_scraped               object
first_review                        object
last_review                         object
requires_license                    object
license                             object
instant_bookable                    object
is_business_travel_ready            object
cancellation_policy                 object
require_guest_profile_picture       object
require_guest_phone_verification    object
dtype: object

### Feature engineering

Let's try to capture as much of this object data as possible.  In this lesson, we'll start with date values.

In [11]:
def find_object_feature_values(df):
    object_features = find_object_features(df)
    return df[object_features][:2].values

In [12]:
find_object_feature_values(df)

array([['https://www.airbnb.com/rooms/2015', '2018-11-07',
        'Berlin-Mitte Value! Quiet courtyard/very central',
        'Great location!  30 of 75 sq meters. This wood floored/high ceiling typical Berlin "Altbau" section of an apartment consists of 1 simple large room, a small kitchen and a bathroom + shower. The apartment is in Mitte, close to Prenzlauer Berg/Mauerpark. Perfect for short visits, singles or couples. Your section is closed from the rest of the bigger flat wich is not noticeable. You will not be sharing your space.',
        'A+++ location! This „Einliegerwohnung“ is an extention of a larger apartment with a separate entrance, bathroom and kitchen. The door to the rest of the apartment is soundproof, hidden, locked and barely noticable (behind mirror in pictures). Your 30 sq meters are facing a quiet courtyard. This wood floored/high ceiling typical Berlin "Altbau" apartment consists of 1 large room with a large double bed, optionally with an extra matress for a 3rd guest), a small kitchen suitable for preparing simple meals, a bathroom + shower + bathtub and of course your own entrance (all linens and towels are provided.) it is located facing a quiet courtyard, it is clean cozy and an authentic "Berlin" place to live. The place is in Mitte, close to Prenzlauer Berg one block from Kastanienallee, Zionskirchplatz, Rosenthaler Platz and Mauerpark. Generally this area is lively with galleries, museums, resturants, cafes, flea markets, bars, clubs, shops, good take away food, a park, U-Bahn, trams, supermarket',
        'Great location!  30 of 75 sq meters. This wood floored/high ceiling typical Berlin "Altbau" section of an apartment consists of 1 simple large room, a small kitchen and a bathroom + shower. The apartment is in Mitte, close to Prenzlauer Berg/Mauerpark. Perfect for short visits, singles or couples. Your section is closed from the rest of the bigger flat wich is not noticeable. You will not be sharing your space. A+++ location! This „Einliegerwohnung“ is an extention of a larger apartment with a separate entrance, bathroom and kitchen. The door to the rest of the apartment is soundproof, hidden, locked and barely noticable (behind mirror in pictures). Your 30 sq meters are facing a quiet courtyard. This wood floored/high ceiling typical Berlin "Altbau" apartment consists of 1 large room with a large double bed, optionally with an extra matress for a 3rd guest), a small kitchen suitable for preparing simple meals, a bathroom + shower + bathtub and of course your own entrance (all linens a',
        'none',
        'It is located in the former East Berlin area of Kastanienallee and Zionskirchplatz (Berlins only natural elevation), very charming and original turn of the last century architecture; this area was barely been destroyed during the war. Close to galleries, resturants, museums, flea markets, cafes, bars, clubs, shops, good take away food, a park, great public transportation: U-Bahn, S-Bahn, Trams, Busses, supermarkets etc.',
        'This is my home, not a hotel. I rent out occasionally when I stay with my friend.',
        'Close to U-Bahn U8 and U2 (metro), Trams M12, M10 and M8, Busses. Rosenthaler Platz and Hackescher Markt are close by. S-Bahn. Alexander Platz is 6 minutes away on the U8 line.',
        'Simple kitchen/cooking, refrigerator, microwave oven, stove, dishwasher, espresso/ coffee mashine, cable TV deskspace, shower, bath tub, little courtyard garden, 1st floor. There is a large double bed and optional additional airbeds for a 3rd or 4th person/kids. (Please note that the apartment is 30 square meters, if you stay a few nights and are more than 2 adults, it will be tight)',
        'Always available',
        'No parties No events No pets No smoking, not even in the courtyard/garden Do not pull the door shut with the keys in the lock from the inside; should that happen, the guest pays for locksmith',
        'https://a0.muscache.com/im/pictures/260fd609-710a-4304-82ab-abd7498efd62.jpg?aki_policy=large',
        'https://www.airbnb.com/users/show/2217', 'Ian', '2008-08-18',
        'Key Biscayne, Florida, United States',
        'Believe in sharing economy.', 'within an hour', '96%', 't',
        'https://a0.muscache.com/im/pictures/21428a22-4f38-444d-8c72-5892be9da109.jpg?aki_policy=profile_small',
        'https://a0.muscache.com/im/pictures/21428a22-4f38-444d-8c72-5892be9da109.jpg?aki_policy=profile_x_medium',
        'Mitte',
        "['email', 'phone', 'reviews', 'jumio', 'offline_government_id', 'government_id']",
        't', 't', 'Berlin, Berlin, Germany', 'Mitte', 'Brunnenstr. Süd',
        'Mitte', 'Berlin', 'Berlin', '10119', 'Berlin',
        'Berlin, Germany', 'DE', 'Germany', 'f', 'Guesthouse',
        'Entire home/apt', 'Real Bed',
        '{TV,"Cable TV",Wifi,Kitchen,Gym,Heating,"Family/kid friendly","Smoke detector",Essentials,Shampoo,"Lock on bedroom door",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Private living room",Bathtub,"Hot water","Bed linens","Extra pillows and blankets",Microwave,"Coffee maker",Refrigerator,Dishwasher,"Dishes and silverware","Cooking basics",Stove,"Luggage dropoff allowed","Long term stays allowed"}',
        '$60.00', nan, nan, '$200.00', '$30.00', '$28.00',
        '3 months ago', 't', '2018-11-07', '2016-04-11', '2018-10-28',
        't', nan, 'f', 'f', 'strict_14_with_grace_period', 'f', 'f'],
       ['https://www.airbnb.com/rooms/2695', '2018-11-07',
        'Prenzlauer Berg close to Mauerpark', nan,
        "In the summertime we are spending most of our weekends in our little house in our garden and want to use the opportunity to rent a room in our cosy 2 bedroom apartment. But we might also stay in the other room. We will be very happy to give you tips on things to do and see in Berlin and make sure your stay runs smoothly. The room is about 25 square meters and is located on the 2nd floor. The bed measures 180 cm x 200 cm and is fitted with a kapok futon, which is a hard-ish mattress but which we find very pleasant to sleep on.  It's a typical Berlin-style apartment located in a friendly and calm neighborhood, plus your room is facing away from the street and into the interior area (so generally very quiet).  All the cafes, bars, shops and other action of the Prenzlauerberg district is easily accessible with a pleasant 10-15 minute stroll across Mauerpark. The main S-Bahn and U-Bahn public transport connections are also just a 10-15 minute walk away. There are all sorts of options for ea",
        "In the summertime we are spending most of our weekends in our little house in our garden and want to use the opportunity to rent a room in our cosy 2 bedroom apartment. But we might also stay in the other room. We will be very happy to give you tips on things to do and see in Berlin and make sure your stay runs smoothly. The room is about 25 square meters and is located on the 2nd floor. The bed measures 180 cm x 200 cm and is fitted with a kapok futon, which is a hard-ish mattress but which we find very pleasant to sleep on.  It's a typical Berlin-style apartment located in a friendly and calm neighborhood, plus your room is facing away from the street and into the interior area (so generally very quiet).  All the cafes, bars, shops and other action of the Prenzlauerberg district is easily accessible with a pleasant 10-15 minute stroll across Mauerpark. The main S-Bahn and U-Bahn public transport connections are also just a 10-15 minute walk away. There are all sorts of options for ea",
        'none', nan, nan,
        "Within walking distance you'll find the S-Bahn, two metro lines,  tram lines and busses.  But the best way to discover Berlin is by bike. Please ask if you need a guest bike.",
        'Außer deinem Zimmer kannst du noch die Küche und das Badezimmer benutzen. Es gibt auch einen Balkon, den man tagsüber benutzen kann. Der Zugang führt allerdings durch unser anderes Zimmer, wo wir dann abends eventuel schlafen.',
        nan, nan,
        'https://a0.muscache.com/im/pictures/97d4f6e8-1c77-47fc-958e-26ba5618083c.jpg?aki_policy=large',
        'https://www.airbnb.com/users/show/2986', 'Michael',
        '2008-09-16', 'Berlin, Berlin, Germany',
        'Living with my wife in Berlin.  Like travelling, hiking, canoing, beach volleyball, yoga, cinema....',
        nan, nan, 'f',
        'https://a0.muscache.com/im/pictures/50434955-1888-4049-bbff-a78464dbfa5a.jpg?aki_policy=profile_small',
        'https://a0.muscache.com/im/pictures/50434955-1888-4049-bbff-a78464dbfa5a.jpg?aki_policy=profile_x_medium',
        'Prenzlauer Berg',
        "['email', 'phone', 'reviews', 'jumio', 'government_id']", 't',
        't', 'Berlin, Berlin, Germany', nan, 'Prenzlauer Berg Nordwest',
        'Pankow', 'Berlin', 'Berlin', '10437', 'Berlin',
        'Berlin, Germany', 'DE', 'Germany', 't', 'Apartment',
        'Private room', 'Real Bed',
        '{Wifi,Kitchen,Elevator,Heating,Washer,Essentials,Shampoo,"Hair dryer","Laptop friendly workspace","Private living room"}',
        '$17.00', nan, nan, '$0.00', '$0.00', '$0.00', '7 weeks ago',
        't', '2018-11-07', '2018-07-04', '2018-10-01', 't', nan, 'f',
        'f', 'flexible', 'f', 'f']], dtype=object)

In [13]:
find_object_feature_values(df)[0, :3]

array(['https://www.airbnb.com/rooms/2015', '2018-11-07',
       'Berlin-Mitte Value! Quiet courtyard/very central'], dtype=object)

We can see that the second column, `last_scraped` should be a date, but is listed as an object.  It would be nice if we could use the `to_datetime` method to put our columns in the correct format.

In [14]:
pd.to_datetime(df['last_scraped'], infer_datetime_format=True)

0       2018-11-07
1       2018-11-07
2       2018-11-07
3       2018-11-07
4       2018-11-07
5       2018-11-07
6       2018-11-07
7       2018-11-07
8       2018-11-07
9       2018-11-07
10      2018-11-07
11      2018-11-07
12      2018-11-07
13      2018-11-07
14      2018-11-07
15      2018-11-07
16      2018-11-07
17      2018-11-07
18      2018-11-07
19      2018-11-07
20      2018-11-07
21      2018-11-07
22      2018-11-07
23      2018-11-07
24      2018-11-07
25      2018-11-07
26      2018-11-07
27      2018-11-07
28      2018-11-07
29      2018-11-07
30      2018-11-07
31      2018-11-07
32      2018-11-07
33      2018-11-07
34      2018-11-07
35      2018-11-07
36      2018-11-07
37      2018-11-07
38      2018-11-07
39      2018-11-07
40      2018-11-07
41      2018-11-07
42      2018-11-07
43      2018-11-07
44      2018-11-07
45      2018-11-07
46      2018-11-07
47      2018-11-07
48      2018-11-07
49      2018-11-07
           ...
22502   2018-11-07
22503   2018-11-07
22504   2018-11-07
22505   2018-11-07
22506   2018-11-07
22507   2018-11-07
22508   2018-11-07
22509   2018-11-07
22510   2018-11-07
22511   2018-11-07
22512   2018-11-07
22513   2018-11-07
22514   2018-11-07
22515   2018-11-07
22516   2018-11-07
22517   2018-11-07
22518   2018-11-07
22519   2018-11-07
22520   2018-11-07
22521   2018-11-07
22522   2018-11-07
22523   2018-11-07
22524   2018-11-07
22525   2018-11-07
22526   2018-11-07
22527   2018-11-07
22528   2018-11-07
22529   2018-11-07
22530   2018-11-07
22531   2018-11-07
22532   2018-11-07
22533   2018-11-07
22534   2018-11-07
22535   2018-11-07
22536   2018-11-07
22537   2018-11-07
22538   2018-11-07
22539   2018-11-07
22540   2018-11-07
22541   2018-11-07
22542   2018-11-07
22543   2018-11-07
22544   2018-11-07
22545   2018-11-07
22546   2018-11-07
22547   2018-11-07
22548   2018-11-07
22549   2018-11-07
22550   2018-11-07
22551   2018-11-07
Name: last_scraped, Length: 22552, dtype: datetime64[ns]

But it doesn't work as well as we would hope. Let's write a method called `is_date` that detects if our column value is a date.

In [15]:
def contains_date(column):
#     remove nas first, potentially use all
    regex_string = (r'^\d{1,2}-\d{1,2}-\d{4}$|^\d{4}-\d{1,2}-\d{1,2}$' + 
'|^\d{1,2}\/\d{1,2}\/\d{4}$|^\d{4}\/\d{1,2}\/\d{1,2}$')
    return column.str.contains(regex_string).any()

The regex above is wild but it's easier to understand once we understand that each `|` means `or`.  So really, we can think of the above regex as multiple different ones.  So the first one of them is:

`^\d{1,2}-\d{1,2}-\d{4}$`

Which means start with one or two digits, then one or two digits again, and then four digits.  With each set of digits separated by a hyphen.

`11-22-2018`

So contains date tells us if any column in the above contains a date.

In [16]:
contains_date(df.last_scraped)

True

In [17]:
contains_date(df.host_since)

True

In [18]:
contains_date(df.house_rules)

False

In [19]:
def find_date_features(df):
    series_contains_date = df.apply(contains_date)
    return series_contains_date.index[series_contains_date.values]

In [20]:
find_date_features(df)

Index(['last_scraped', 'host_since', 'calendar_last_scraped', 'first_review',
       'last_review'],
      dtype='object')

In [21]:
date_features = find_date_features(df)

In [22]:
date_features

Index(['last_scraped', 'host_since', 'calendar_last_scraped', 'first_review',
       'last_review'],
      dtype='object')

Now we can set those features to be date time.

In [23]:
def to_dates(df):
    date_features = find_date_features(df)
    return df[date_features].astype('datetime64[ns]')

In [24]:
df_date_features = to_dates(df)

In [25]:
df_date_features

      last_scraped host_since calendar_last_scraped first_review last_review
0       2018-11-07 2008-08-18            2018-11-07   2016-04-11  2018-10-28
1       2018-11-07 2008-09-16            2018-11-07   2018-07-04  2018-10-01
2       2018-11-07 2008-10-19            2018-11-07   2009-06-20  2017-03-20
3       2018-11-07 2008-11-07            2018-11-07   2013-08-12  2018-08-16
4       2018-11-07 2009-05-16            2018-11-07   2009-08-18  2018-11-04
5       2018-11-07 2009-08-25            2018-11-07   2015-08-09  2018-07-23
6       2018-11-07 2009-11-18            2018-11-07   2010-06-29  2018-11-01
7       2018-11-07 2009-12-03            2018-11-07          NaT         NaT
8       2018-11-07 2009-12-20            2018-11-07   2010-06-04  2017-12-14
9       2018-11-07 2010-01-04            2018-11-07   2010-10-07  2018-10-31
10      2018-11-07 2010-01-08            2018-11-07   2010-02-18  2018-10-30
11      2018-11-07 2010-01-18            2018-11-07   2012-10-03  2018-10-20
12      2018-11-07 2009-12-20            2018-11-07   2010-09-23  2016-06-05
13      2018-11-07 2010-02-27            2018-11-07   2010-05-15  2018-10-01
14      2018-11-07 2010-03-02            2018-11-07   2010-10-10  2018-11-05
15      2018-11-07 2010-03-17            2018-11-07   2010-06-07  2018-06-30
16      2018-11-07 2010-03-27            2018-11-07   2010-09-22  2018-08-25
17      2018-11-07 2010-03-27            2018-11-07   2010-09-07  2016-08-14
18      2018-11-07 2010-04-23            2018-11-07   2010-08-17  2018-11-05
19      2018-11-07 2009-11-18            2018-11-07   2010-11-23  2017-04-29
20      2018-11-07 2010-05-10            2018-11-07   2011-06-29  2017-08-02
21      2018-11-07 2010-02-22            2018-11-07   2013-08-13  2013-08-13
22      2018-11-07 2009-11-14            2018-11-07   2010-09-29  2018-07-31
23      2018-11-07 2011-04-05            2018-11-07   2010-09-16  2018-10-31
24      2018-11-07 2010-05-30            2018-11-07   2018-05-22  2018-10-28
25      2018-11-07 2010-06-12            2018-11-07   2010-08-19  2018-11-04
26      2018-11-07 2010-06-27            2018-11-07   2010-09-16  2010-09-16
27      2018-11-07 2010-07-02            2018-11-07   2017-03-09  2018-10-19
28      2018-11-07 2010-07-06            2018-11-07   2010-07-31  2018-09-25
29      2018-11-07 2010-06-21            2018-11-07   2010-07-24  2018-10-04
30      2018-11-07 2010-10-27            2018-11-07   2010-07-17  2018-10-30
31      2018-11-07 2010-07-11            2018-11-07   2010-09-16  2018-07-21
32      2018-11-07 2010-07-12            2018-11-07   2010-07-28  2012-07-27
33      2018-11-07 2010-07-20            2018-11-07   2012-04-07  2016-09-26
34      2018-11-07 2010-07-24            2018-11-07   2010-08-23  2017-10-08
35      2018-11-07 2010-07-25            2018-11-07   2014-09-26  2014-09-26
36      2018-11-07 2010-10-27            2018-11-07   2012-05-05  2018-10-01
37      2018-11-07 2010-07-31            2018-11-07   2010-12-31  2018-11-04
38      2018-11-07 2010-08-01            2018-11-07   2010-10-02  2018-10-31
39      2018-11-07 2010-08-06            2018-11-07   2011-01-05  2018-10-01
40      2018-11-07 2010-08-08            2018-11-07   2010-09-27  2018-10-09
41      2018-11-07 2010-08-15            2018-11-07   2011-03-23  2018-03-11
42      2018-11-07 2010-08-19            2018-11-07   2012-04-17  2018-08-29
43      2018-11-07 2010-08-31            2018-11-07   2010-09-27  2018-09-29
44      2018-11-07 2010-08-24            2018-11-07          NaT         NaT
45      2018-11-07 2010-04-22            2018-11-07   2012-10-29  2016-10-21
46      2018-11-07 2010-10-11            2018-11-07   2010-11-04  2018-10-14
47      2018-11-07 2010-10-13            2018-11-07          NaT         NaT
48      2018-11-07 2010-10-14            2018-11-07   2011-01-26  2011-01-26
49      2018-11-07 2010-10-17            2018-11-07   2013-03-12  2016-03-12
...            ...        ...                   ...          ...         ...
22502   2018-11-07 2013-08-19            2018-11-07          NaT         NaT
22503   2018-11-07 2018-03-09            2018-11-07          NaT         NaT
22504   2018-11-07 2016-12-25            2018-11-07          NaT         NaT
22505   2018-11-07 2014-04-13            2018-11-07          NaT         NaT
22506   2018-11-07 2016-01-08            2018-11-07          NaT         NaT
22507   2018-11-07 2011-04-06            2018-11-07          NaT         NaT
22508   2018-11-07 2018-11-05            2018-11-07   2018-11-07  2018-11-07
22509   2018-11-07 2018-11-05            2018-11-07          NaT         NaT
22510   2018-11-07 2016-06-13            2018-11-07          NaT         NaT
22511   2018-11-07 2017-10-01            2018-11-07          NaT         NaT
22512   2018-11-07 2015-09-02            2018-11-07          NaT         NaT
22513   2018-11-07 2017-10-16            2018-11-07          NaT         NaT
22514   2018-11-07 2015-10-21            2018-11-07          NaT         NaT
22515   2018-11-07 2017-03-16            2018-11-07          NaT         NaT
22516   2018-11-07 2018-11-05            2018-11-07          NaT         NaT
22517   2018-11-07 2018-10-30            2018-11-07          NaT         NaT
22518   2018-11-07 2018-04-05            2018-11-07          NaT         NaT
22519   2018-11-07 2018-11-05            2018-11-07          NaT         NaT
22520   2018-11-07 2018-09-16            2018-11-07          NaT         NaT
22521   2018-11-07 2018-04-29            2018-11-07          NaT         NaT
22522   2018-11-07 2017-05-22            2018-11-07          NaT         NaT
22523   2018-11-07 2018-08-19            2018-11-07          NaT         NaT
22524   2018-11-07 2012-01-23            2018-11-07          NaT         NaT
22525   2018-11-07 2015-08-09            2018-11-07          NaT         NaT
22526   2018-11-07 2017-08-08            2018-11-07          NaT         NaT
22527   2018-11-07 2017-08-08            2018-11-07          NaT         NaT
22528   2018-11-07 2013-05-12            2018-11-07          NaT         NaT
22529   2018-11-07 2016-06-08            2018-11-07          NaT         NaT
22530   2018-11-07 2013-02-18            2018-11-07          NaT         NaT
22531   2018-11-07 2012-09-19            2018-11-07          NaT         NaT
22532   2018-11-07 2014-01-11            2018-11-07          NaT         NaT
22533   2018-11-07 2018-02-16            2018-11-07          NaT         NaT
22534   2018-11-07 2018-07-16            2018-11-07          NaT         NaT
22535   2018-11-07 2018-07-16            2018-11-07          NaT         NaT
22536   2018-11-07 2011-05-20            2018-11-07   2018-11-07  2018-11-07
22537   2018-11-07 2018-07-16            2018-11-07          NaT         NaT
22538   2018-11-07 2017-05-04            2018-11-07          NaT         NaT
22539   2018-11-07 2012-06-03            2018-11-07          NaT         NaT
22540   2018-11-07 2015-01-21            2018-11-07          NaT         NaT
22541   2018-11-07 2014-09-05            2018-11-07          NaT         NaT
22542   2018-11-07 2018-11-06            2018-11-07          NaT         NaT
22543   2018-11-07 2017-02-17            2018-11-07          NaT         NaT
22544   2018-11-07 2013-10-20            2018-11-07          NaT         NaT
22545   2018-11-07 2018-01-02            2018-11-07          NaT         NaT
22546   2018-11-07 2014-09-15            2018-11-07          NaT         NaT
22547   2018-11-07 2016-08-02            2018-11-07          NaT         NaT
22548   2018-11-07 2016-04-17            2018-11-07          NaT         NaT
22549   2018-11-07 2012-08-03            2018-11-07          NaT         NaT
22550   2018-11-07 2015-06-28            2018-11-07          NaT         NaT
22551   2018-11-07 2018-03-09            2018-11-07          NaT         NaT

[22552 rows x 5 columns]

In [26]:
df_date_features.dtypes

last_scraped             datetime64[ns]
host_since               datetime64[ns]
calendar_last_scraped    datetime64[ns]
first_review             datetime64[ns]
last_review              datetime64[ns]
dtype: object

In [27]:
df_date_features.dtypes

# last_scraped             datetime64[ns]
# host_since               datetime64[ns]
# calendar_last_scraped    datetime64[ns]
# first_review             datetime64[ns]
# last_review              datetime64[ns]

df_date_features[:3]

  last_scraped host_since calendar_last_scraped first_review last_review
0   2018-11-07 2008-08-18            2018-11-07   2016-04-11  2018-10-28
1   2018-11-07 2008-09-16            2018-11-07   2018-07-04  2018-10-01
2   2018-11-07 2008-10-19            2018-11-07   2009-06-20  2017-03-20

In [28]:
# make it work
# make it right
# make it fast

In [29]:
from date_lib import add_datepart

In [30]:
copied_df = df.copy()
add_datepart(copied_df, 'last_scraped')

In [31]:
# 1. periodic data
# 2. external data
#     * weather
# 3. differences within a row or differences between rows
# first listing

In [32]:
copied_df.columns

Index(['id', 'listing_url', 'scrape_id', 'name', 'summary', 'space',
       'description', 'experiences_offered', 'neighborhood_overview', 'notes',
       ...
       'last_scrapedDay', 'last_scrapedDayofweek', 'last_scrapedDayofyear',
       'last_scrapedIs_month_end', 'last_scrapedIs_month_start',
       'last_scrapedIs_quarter_end', 'last_scrapedIs_quarter_start',
       'last_scrapedIs_year_end', 'last_scrapedIs_year_start',
       'last_scrapedElapsed'],
      dtype='object', length=108)

In [33]:
len(copied_df.columns)

108

In [34]:
len(df.columns)

96

In [35]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

In [36]:
copied_df.head(2)

,id,listing_url,scrape_id,name,summary,space,description,experiences_offered,neighborhood_overview,notes,...,last_scrapedDay,last_scrapedDayofweek,last_scrapedDayofyear,last_scrapedIs_month_end,last_scrapedIs_month_start,last_scrapedIs_quarter_end,last_scrapedIs_quarter_start,last_scrapedIs_year_end,last_scrapedIs_year_start,last_scrapedElapsed
0,2015,https://www.airbnb.com/rooms/2015,20181107122246,Berlin-Mitte Value! Quiet courtyard/very central,Great location! 30 of 75 sq meters. This wood...,A+++ location! This „Einliegerwohnung“ is an e...,Great location! 30 of 75 sq meters. This wood...,none,It is located in the former East Berlin area o...,"This is my home, not a hotel. I rent out occas...",...,7,2,311,False,False,False,False,False,False,1541548800
1,2695,https://www.airbnb.com/rooms/2695,20181107122246,Prenzlauer Berg close to Mauerpark,NaN,In the summertime we are spending most of our ...,In the summertime we are spending most of our ...,none,NaN,NaN,...,7,2,311,False,False,False,False,False,False,1541548800

In [37]:
df.head(2)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2015,https://www.airbnb.com/rooms/2015,20181107122246,2018-11-07,Berlin-Mitte Value! Quiet courtyard/very central,Great location! 30 of 75 sq meters. This wood...,A+++ location! This „Einliegerwohnung“ is an e...,Great location! 30 of 75 sq meters. This wood...,none,It is located in the former East Berlin area o...,...,t,NaN,NaN,f,f,strict_14_with_grace_period,f,f,4,3.76
1,2695,https://www.airbnb.com/rooms/2695,20181107122246,2018-11-07,Prenzlauer Berg close to Mauerpark,NaN,In the summertime we are spending most of our ...,In the summertime we are spending most of our ...,none,NaN,...,t,NaN,NaN,f,f,flexible,f,f,1,1.42

In [38]:
def generate_new_date_columns(dates_df):
    copied_dates_df = dates_df.copy()
    for col in copied_dates_df.columns:
        add_datepart(copied_dates_df, col)
    return copied_dates_df

In [39]:
generate_new_date_columns(df_date_features)

,last_scrapedYear,last_scrapedMonth,last_scrapedWeek,last_scrapedDay,last_scrapedDayofweek,last_scrapedDayofyear,last_scrapedIs_month_end,last_scrapedIs_month_start,last_scrapedIs_quarter_end,last_scrapedIs_quarter_start,...,last_reviewDay,last_reviewDayofweek,last_reviewDayofyear,last_reviewIs_month_end,last_reviewIs_month_start,last_reviewIs_quarter_end,last_reviewIs_quarter_start,last_reviewIs_year_end,last_reviewIs_year_start,last_reviewElapsed
0,2018,11,45,7,2,311,False,False,False,False,...,28.0,6.0,301.0,False,False,False,False,False,False,1540684800
1,2018,11,45,7,2,311,False,False,False,False,...,1.0,0.0,274.0,False,True,False,True,False,False,1538352000
2,2018,11,45,7,2,311,False,False,False,False,...,20.0,0.0,79.0,False,False,False,False,False,False,1489968000
3,2018,11,45,7,2,311,False,False,False,False,...,16.0,3.0,228.0,False,False,False,False,False,False,1534377600
4,2018,11,45,7,2,311,False,False,False,False,...,4.0,6.0,308.0,False,False,False,False,False,False,1541289600
5,2018,11,45,7,2,311,False,False,False,False,...,23.0,0.0,204.0,False,False,False,False,False,False,1532304000
6,2018,11,45,7,2,311,False,False,False,False,...,1.0,3.0,305.0,False,True,False,False,False,False,1541030400
7,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
8,2018,11,45,7,2,311,False,False,False,False,...,14.0,3.0,348.0,False,False,False,False,False,False,1513209600
9,2018,11,45,7,2,311,False,False,False,False,...,31.0,2.0,304.0,True,False,False,False,False,False,1540944000
10,2018,11,45,7,2,311,False,False,False,False,...,30.0,1.0,303.0,False,False,False,False,False,False,1540857600
11,2018,11,45,7,2,311,False,False,False,False,...,20.0,5.0,293.0,False,False,False,False,False,False,1539993600
12,2018,11,45,7,2,311,False,False,False,False,...,5.0,6.0,157.0,False,False,False,False,False,False,1465084800
13,2018,11,45,7,2,311,False,False,False,False,...,1.0,0.0,274.0,False,True,False,True,False,False,1538352000
14,2018,11,45,7,2,311,False,False,False,False,...,5.0,0.0,309.0,False,False,False,False,False,False,1541376000
15,2018,11,45,7,2,311,False,False,False,False,...,30.0,5.0,181.0,True,False,True,False,False,False,1530316800
16,2018,11,45,7,2,311,False,False,False,False,...,25.0,5.0,237.0,False,False,False,False,False,False,1535155200
17,2018,11,45,7,2,311,False,False,False,False,...,14.0,6.0,227.0,False,False,False,False,False,False,1471132800
18,2018,11,45,7,2,311,False,False,False,False,...,5.0,0.0,309.0,False,False,False,False,False,False,1541376000
19,2018,11,45,7,2,311,False,False,False,False,...,29.0,5.0,119.0,False,False,False,False,False,False,1493424000
20,2018,11,45,7,2,311,False,False,False,False,...,2.0,2.0,214.0,False,False,False,False,False,False,1501632000
21,2018,11,45,7,2,311,False,False,False,False,...,13.0,1.0,225.0,False,False,False,False,False,False,1376352000
22,2018,11,45,7,2,311,False,False,False,False,...,31.0,1.0,212.0,True,False,False,False,False,False,1532995200
23,2018,11,45,7,2,311,False,False,False,False,...,31.0,2.0,304.0,True,False,False,False,False,False,1540944000
24,2018,11,45,7,2,311,False,False,False,False,...,28.0,6.0,301.0,False,False,False,False,False,False,1540684800
25,2018,11,45,7,2,311,False,False,False,False,...,4.0,6.0,308.0,False,False,False,False,False,False,1541289600
26,2018,11,45,7,2,311,False,False,False,False,...,16.0,3.0,259.0,False,False,False,False,False,False,1284595200
27,2018,11,45,7,2,311,False,False,False,False,...,19.0,4.0,292.0,False,False,False,False,False,False,1539907200
28,2018,11,45,7,2,311,False,False,False,False,...,25.0,1.0,268.0,False,False,False,False,False,False,1537833600
29,2018,11,45,7,2,311,False,False,False,False,...,4.0,3.0,277.0,False,False,False,False,False,False,1538611200
30,2018,11,45,7,2,311,False,False,False,False,...,30.0,1.0,303.0,False,False,False,False,False,False,1540857600
31,2018,11,45,7,2,311,False,False,False,False,...,21.0,5.0,202.0,False,False,False,False,False,False,1532131200
32,2018,11,45,7,2,311,False,False,False,False,...,27.0,4.0,209.0,False,False,False,False,False,False,1343347200
33,2018,11,45,7,2,311,False,False,False,False,...,26.0,0.0,270.0,False,False,False,False,False,False,1474848000
34,2018,11,45,7,2,311,False,False,False,False,...,8.0,6.0,281.0,False,False,False,False,False,False,1507420800
35,2018,11,45,7,2,311,False,False,False,False,...,26.0,4.0,269.0,False,False,False,False,False,False,1411689600
36,2018,11,45,7,2,311,False,False,False,False,...,1.0,0.0,274.0,False,True,False,True,False,False,1538352000
37,2018,11,45,7,2,311,False,False,False,False,...,4.0,6.0,308.0,False,False,False,False,False,False,1541289600
38,2018,11,45,7,2,311,False,False,False,False,...,31.0,2.0,304.0,True,False,False,False,False,False,1540944000
39,2018,11,45,7,2,311,False,False,False,False,...,1.0,0.0,274.0,False,True,False,True,False,False,1538352000
40,2018,11,45,7,2,311,False,False,False,False,...,9.0,1.0,282.0,False,False,False,False,False,False,1539043200
41,2018,11,45,7,2,311,False,False,False,False,...,11.0,6.0,70.0,False,False,False,False,False,False,1520726400
42,2018,11,45,7,2,311,False,False,False,False,...,29.0,2.0,241.0,False,False,False,False,False,False,1535500800
43,2018,11,45,7,2,311,False,False,False,False,...,29.0,5.0,272.0,False,False,False,False,False,False,1538179200
44,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
45,2018,11,45,7,2,311,False,False,False,False,...,21.0,4.0,295.0,False,False,False,False,False,False,1477008000
46,2018,11,45,7,2,311,False,False,False,False,...,14.0,6.0,287.0,False,False,False,False,False,False,1539475200
47,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
48,2018,11,45,7,2,311,False,False,False,False,...,26.0,2.0,26.0,False,False,False,False,False,False,1296000000
49,2018,11,45,7,2,311,False,False,False,False,...,12.0,5.0,72.0,False,False,False,False,False,False,1457740800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22502,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22503,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22504,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22505,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22506,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22507,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22508,2018,11,45,7,2,311,False,False,False,False,...,7.0,2.0,311.0,False,False,False,False,False,False,1541548800
22509,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22510,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22511,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22512,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22513,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22514,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22515,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22516,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22517,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22518,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22519,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22520,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22521,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22522,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22523,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22524,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22525,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22526,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22527,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22528,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22529,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22530,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22531,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22532,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22533,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22534,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22535,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22536,2018,11,45,7,2,311,False,False,False,False,...,7.0,2.0,311.0,False,False,False,False,False,False,1541548800
22537,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22538,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22539,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22540,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22541,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22542,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22543,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22544,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22545,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22546,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22547,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22548,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22549,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22550,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037
22551,2018,11,45,7,2,311,False,False,False,False,...,NaN,NaN,NaN,False,False,False,False,False,False,-9223372037

In [40]:
new_date_col_df = generate_new_date_columns(df_date_features)

In [41]:
len(new_date_col_df.columns)

65

In [42]:
len(df_date_features.columns)

5

In [43]:
new_date_col_df.columns

Index(['last_scrapedYear', 'last_scrapedMonth', 'last_scrapedWeek',
       'last_scrapedDay', 'last_scrapedDayofweek', 'last_scrapedDayofyear',
       'last_scrapedIs_month_end', 'last_scrapedIs_month_start',
       'last_scrapedIs_quarter_end', 'last_scrapedIs_quarter_start',
       'last_scrapedIs_year_end', 'last_scrapedIs_year_start',
       'last_scrapedElapsed', 'host_sinceYear', 'host_sinceMonth',
       'host_sinceWeek', 'host_sinceDay', 'host_sinceDayofweek',
       'host_sinceDayofyear', 'host_sinceIs_month_end',
       'host_sinceIs_month_start', 'host_sinceIs_quarter_end',
       'host_sinceIs_quarter_start', 'host_sinceIs_year_end',
       'host_sinceIs_year_start', 'host_sinceElapsed',
       'calendar_last_scrapedYear', 'calendar_last_scrapedMonth',
       'calendar_last_scrapedWeek', 'calendar_last_scrapedDay',
       'calendar_last_scrapedDayofweek', 'calendar_last_scrapedDayofyear',
       'calendar_last_scrapedIs_month_end',
       'calendar_last_scrapedIs_month_start',
       'calendar_last_scrapedIs_quarter_end',
       'calendar_last_scrapedIs_quarter_start',
       'calendar_last_scrapedIs_year_end',
       'calendar_last_scrapedIs_year_start', 'calendar_last_scrapedElapsed',
       'first_reviewYear', 'first_reviewMonth', 'first_reviewWeek',
       'first_reviewDay', 'first_reviewDayofweek', 'first_reviewDayofyear',
       'first_reviewIs_month_end', 'first_reviewIs_month_start',
       'first_reviewIs_quarter_end', 'first_reviewIs_quarter_start',
       'first_reviewIs_year_end', 'first_reviewIs_year_start',
       'first_reviewElapsed', 'last_reviewYear', 'last_reviewMonth',
       'last_reviewWeek', 'last_reviewDay', 'last_reviewDayofweek',
       'last_reviewDayofyear', 'last_reviewIs_month_end',
       'last_reviewIs_month_start', 'last_reviewIs_quarter_end',
       'last_reviewIs_quarter_start', 'last_reviewIs_year_end',
       'last_reviewIs_year_start', 'last_reviewElapsed'],
      dtype='object')

In [44]:
df_date_features.columns

Index(['last_scraped', 'host_since', 'calendar_last_scraped', 'first_review',
       'last_review'],
      dtype='object')

Once coercing our dates, we can merge with the original dataframe, and replace each of the old columns that should be dates.

In [45]:
def merge_dfs(original_df, new_df):
    copied_original = original_df.copy()
    date_features = find_date_features(original_df)
    copied_dropped = copied_original.drop(columns = date_features)
    copied_dropped[new_df.columns] = new_df
    return copied_dropped

In [46]:
merge_dfs(df, new_date_col_df).head(2).T

,0,1
id,2015,2695
listing_url,https://www.airbnb.com/rooms/2015,https://www.airbnb.com/rooms/2695
scrape_id,20181107122246,20181107122246
name,Berlin-Mitte Value! Quiet courtyard/very central,Prenzlauer Berg close to Mauerpark
summary,Great location! 30 of 75 sq meters. This wood...,NaN
space,A+++ location! This „Einliegerwohnung“ is an e...,In the summertime we are spending most of our ...
description,Great location! 30 of 75 sq meters. This wood...,In the summertime we are spending most of our ...
experiences_offered,none,none
neighborhood_overview,It is located in the former East Berlin area o...,NaN
notes,"This is my home, not a hotel. I rent out occas...",NaN
transit,"Close to U-Bahn U8 and U2 (metro), Trams M12, ...",Within walking distance you'll find the S-Bahn...
access,"Simple kitchen/cooking, refrigerator, microwav...",Außer deinem Zimmer kannst du noch die Küche u...
interaction,Always available,NaN
house_rules,"No parties No events No pets No smoking, not e...",NaN
thumbnail_url,NaN,NaN
medium_url,NaN,NaN
picture_url,https://a0.muscache.com/im/pictures/260fd609-7...,https://a0.muscache.com/im/pictures/97d4f6e8-1...
xl_picture_url,NaN,NaN
host_id,2217,2986
host_url,https://www.airbnb.com/users/show/2217,https://www.airbnb.com/users/show/2986
host_name,Ian,Michael
host_location,"Key Biscayne, Florida, United States","Berlin, Berlin, Germany"
host_about,Believe in sharing economy.,Living with my wife in Berlin. Like travellin...
host_response_time,within an hour,NaN
host_response_rate,96%,NaN
host_acceptance_rate,NaN,NaN
host_is_superhost,t,f
host_thumbnail_url,https://a0.muscache.com/im/pictures/21428a22-4...,https://a0.muscache.com/im/pictures/50434955-1...
host_picture_url,https://a0.muscache.com/im/pictures/21428a22-4...,https://a0.muscache.com/im/pictures/50434955-1...
host_neighbourhood,Mitte,Prenzlauer Berg
host_listings_count,4,1
host_total_listings_count,4,1
host_verifications,"['email', 'phone', 'reviews', 'jumio', 'offlin...","['email', 'phone', 'reviews', 'jumio', 'govern..."
host_has_profile_pic,t,t
host_identity_verified,t,t
street,"Berlin, Berlin, Germany","Berlin, Berlin, Germany"
neighbourhood,Mitte,NaN
neighbourhood_cleansed,Brunnenstr. Süd,Prenzlauer Berg Nordwest
neighbourhood_group_cleansed,Mitte,Pankow
city,Berlin,Berlin
state,Berlin,Berlin
zipcode,10119,10437
market,Berlin,Berlin
smart_location,"Berlin, Germany","Berlin, Germany"
country_code,DE,DE
country,Germany,Germany
latitude,52.5345,52.5485
longitude,13.4026,13.4046
is_location_exact,f,t
property_type,Guesthouse,Apartment
...,...,...
host_sinceWeek,34,38
host_sinceDay,18,16
host_sinceDayofweek,0,1
host_sinceDayofyear,231,260
host_sinceIs_month_end,False,False
host_sinceIs_month_start,False,False
host_sinceIs_quarter_end,False,False
host_sinceIs_quarter_start,False,False
host_sinceIs_year_end,False,False
host_sinceIs_year_start,False,False
host_sinceElapsed,1219017600,1221523200
calendar_last_scrapedYear,2018,2018
calendar_last_scrapedMonth,11,11
calendar_last_scrapedWeek,45,45
calendar_last_scrapedDay,7,7
calendar_last_scrapedDayofweek,2,2
calendar_last_scrapedDayofyear,311,311
calendar_last_scrapedIs_month_end,False,False
calendar_last_scrapedIs_month_start,False,False
calendar_last_scrapedIs_quarter_end,False,False
calendar_last_scrapedIs_quarter_start,False,False
calendar_last_scrapedIs_year_end,False,False
calendar_last_scrapedIs_year_start,False,False
calendar_last_scrapedElapsed,1541548800,1541548800
first_reviewYear,2016,2018
first_reviewMonth,4,7
first_reviewWeek,15,27
first_reviewDay,11,4
first_reviewDayofweek,0,2
first_reviewDayofyear,102,185
first_reviewIs_month_end,False,False
first_reviewIs_month_start,False,False
first_reviewIs_quarter_end,False,False
first_reviewIs_quarter_start,False,False
first_reviewIs_year_end,False,False
first_reviewIs_year_start,False,False
first_reviewElapsed,1460332800,1530662400
last_reviewYear,2018,2018
last_reviewMonth,10,10
last_reviewWeek,43,40
last_reviewDay,28,1
last_reviewDayofweek,6,0
last_reviewDayofyear,301,274
last_reviewIs_month_end,False,False
last_reviewIs_month_start,False,True
last_reviewIs_quarter_end,False,False
last_reviewIs_quarter_start,False,True
last_reviewIs_year_end,False,False
last_reviewIs_year_start,False,False
last_reviewElapsed,1540684800,1538352000

In [47]:
merge_dfs(df, new_date_col_df).columns

Index(['id', 'listing_url', 'scrape_id', 'name', 'summary', 'space',
       'description', 'experiences_offered', 'neighborhood_overview', 'notes',
       ...
       'last_reviewDay', 'last_reviewDayofweek', 'last_reviewDayofyear',
       'last_reviewIs_month_end', 'last_reviewIs_month_start',
       'last_reviewIs_quarter_end', 'last_reviewIs_quarter_start',
       'last_reviewIs_year_end', 'last_reviewIs_year_start',
       'last_reviewElapsed'],
      dtype='object', length=156)

In [48]:
new_df = merge_dfs(df, new_date_col_df)

We can confirm that the `new_df` has fewer `object_feature` columns than the original.

In [49]:
# new_df = new_df.drop(columns = remaining_date_features)
len(find_object_features(new_df))

57

In [50]:
len(find_object_features(df))

62

Even though our `new_df` has more features.

In [51]:
len(new_df.columns)

156

### Working with Trickier Dates

Sometimes we'll have have some features that represents a date, but is worded as text.  For example, the text '6 years ago' could be translated into a date.  Let's write a function that finds this features with this text.  And also write functions to coerce this data into the proper format.

In [52]:
def contains_time_ago(column):
    regex_string = (r'^\d.*ago$')
    return column.str.contains(regex_string).any()

In [53]:
def find_time_ago_features(df):
    series_contains_time_ago = df.apply(contains_time_ago)
    return series_contains_time_ago.index[series_contains_time_ago.values]

In [54]:
find_time_ago_features(df)

Index(['calendar_updated'], dtype='object')

In [55]:
from date_lib import get_past_date

In [56]:
calendar_updated = df.calendar_updated.apply(get_past_date).astype('datetime64[ns]')

In [57]:
calendar_updated.dtypes

dtype('<M8[ns]')

In [58]:
calendar_updated[0:12]

0    2019-05-04
1    2019-06-16
2    2019-07-28
3    2019-07-07
4    2019-08-01
5    2019-07-21
6    2019-08-04
7           NaT
8    2019-06-04
9    2019-07-28
10   2019-07-30
11   2019-08-02
Name: calendar_updated, dtype: datetime64[ns]

Now we can replace our `calendar_updated` column.

### Generating New Features

There are some additional features that we did not generate.  For example, subtracting date columns from another and also subtracting dates from additional key dates like holidays.  Finally, to be even more ambitious, we could match dates to past temperatures if we believe this would help our dataset.

### Summary