# Feature engineering

## my data in use: Automobile (insurance) Data Set 
http://mlr.cs.umass.edu/ml/datasets/Automobile

In [1]:
import pandas as pd

df1 = pd.read_csv("http://mlr.cs.umass.edu/ml/machine-learning-databases/autos/imports-85.data", header=None)
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [2]:
#checking the number of rows and columns
df1.shape

(205, 26)

In [3]:
#assigning the column names
df1.columns = ['symboling',
             'normalized_losses',
             'make',
             'fuel_type',
             'aspiration',
             'num_of_doors',
             'body_style',
             'drive_wheels',
             'engine_location',
             'wheel-base',
             'length',
             'width',
             'height',
             'curb_weight',
             'engine_type',
             'num_of_cylinders',
             'engine_size',
             'fuel_system',
             'bore',
             'stroke',
             'compression_ratio',
             'horsepower',
             'peak_rpm',
             'city_mpg',
             'highway_mpg',
             'price']

In [4]:
df1.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'num_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel-base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'num_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [5]:
df1.head(3)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500

- By looking at the dataframe df1, I noticed that missing values were recorded as "?" instead of NaN. Hence, I decided to write a method to replace "?" into numpy NaN(Not a Number) as below.

### My created method 1: replacing '?' into numpy NaN(Not a Number).

In [6]:
import numpy as np

# 1. My created method 1: replacing '?' into numpy Not A Number.

def replaced_df(df):
    df = df.replace({'?':np.nan}, inplace = True)
    return df

In [7]:
replaced_df(df1)

In [8]:
df1.head(3)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500

In [9]:
#concise summary of df dataframe
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null object
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_of_doors         203 non-null object
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_of_cylinders     205 non-null object
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null object
stroke               201 non-null object
compression_ratio    205 non-null float64
horsepower           203 non-null object
peak_rpm             203 non-null object
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [10]:
df1.describe()

,symboling,wheel-base,length,width,height,curb_weight,engine_size,compression_ratio,city_mpg,highway_mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [11]:
pd.set_option('display.max_rows', 100)

In [12]:
df1.head(2)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500

In [13]:
# checking if there is null value in each column
df1.isnull().any(axis=0)

symboling            False
normalized_losses     True
make                 False
fuel_type            False
aspiration           False
num_of_doors          True
body_style           False
drive_wheels         False
engine_location      False
wheel-base           False
length               False
width                False
height               False
curb_weight          False
engine_type          False
num_of_cylinders     False
engine_size          False
fuel_system          False
bore                  True
stroke                True
compression_ratio    False
horsepower            True
peak_rpm              True
city_mpg             False
highway_mpg          False
price                 True
dtype: bool

In [14]:
# looking for na values
def nas_sorted(df):
    return df.isnull().sum().sort_values(ascending = False)

In [15]:
sorted_nas = nas_sorted(df1)

In [16]:
sorted_nas

normalized_losses    41
price                 4
stroke                4
bore                  4
peak_rpm              2
horsepower            2
num_of_doors          2
length                0
make                  0
fuel_type             0
aspiration            0
body_style            0
drive_wheels          0
engine_location       0
wheel-base            0
height                0
width                 0
highway_mpg           0
curb_weight           0
engine_type           0
num_of_cylinders      0
engine_size           0
fuel_system           0
compression_ratio     0
city_mpg              0
symboling             0
dtype: int64

In [17]:
#concise summary of df dataframe
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null object
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_of_doors         203 non-null object
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_of_cylinders     205 non-null object
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null object
stroke               201 non-null object
compression_ratio    205 non-null float64
horsepower           203 non-null object
peak_rpm             203 non-null object
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [18]:
df1.head().T

                             0            1            2      3      4
symboling                    3            3            1      2      2
normalized_losses          NaN          NaN          NaN    164    164
make               alfa-romero  alfa-romero  alfa-romero   audi   audi
fuel_type                  gas          gas          gas    gas    gas
aspiration                 std          std          std    std    std
num_of_doors               two          two          two   four   four
body_style         convertible  convertible    hatchback  sedan  sedan
drive_wheels               rwd          rwd          rwd    fwd    4wd
engine_location          front        front        front  front  front
wheel-base                88.6         88.6         94.5   99.8   99.4
length                   168.8        168.8        171.2  176.6  176.6
width                     64.1         64.1         65.5   66.2   66.4
height                    48.8         48.8         52.4   54.3   54.3
curb_weight               2548         2548         2823   2337   2824
engine_type               dohc         dohc         ohcv    ohc    ohc
num_of_cylinders          four         four          six   four   five
engine_size                130          130          152    109    136
fuel_system               mpfi         mpfi         mpfi   mpfi   mpfi
bore                      3.47         3.47         2.68   3.19   3.19
stroke                    2.68         2.68         3.47   3.40   3.40
compression_ratio            9            9            9     10      8
horsepower                 111          111          154    102    115
peak_rpm                  5000         5000         5000   5500   5500
city_mpg                    21           21           19     24     18
highway_mpg                 27           27           26     30     22
price                    13495        16500        16500  13950  17450

In [19]:
df1['price'].dtype

dtype('O')

- By looking at the information about the dataframe df1 and the values in "price" columns, which is type "object", I decided to write a method to convert object data type into numeric data type as below.

### My created method 2 : Converting object data type into numeric data type

In [20]:
# My created method 2: converting object data type into numeric data type.

import pandas as pd

def convert_numeric(df, column):
    df[column] = pd.to_numeric(df[column])
    return df

In [21]:
convert_numeric(df1, 'price')

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,15250.0
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,18920.0
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.30,140,5500,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16430.0
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16925.0
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,20970.0
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121,4250,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182,5400,15,20,36880.0
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151.0
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295.0
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575.0
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572.0
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377.0
23,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,7957.0
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229.0
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692.0
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,7609.0
27,1,148,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,8558.0
28,-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88,5000,24,30,8921.0
29,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.00,145,5000,19,24,12964.0
30,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.60,58,4800,49,54,6479.0
31,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76,6000,31,38,6855.0
32,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.10,60,5500,38,42,5399.0
33,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,6529.0
34,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7129.0
35,0,110,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7295.0
36,0,78,honda,gas,std,four,wagon,fwd,front,96.5,...,92,1bbl,2.92,3.41,9.20,76,6000,30,34,7295.0
37,0,106,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,7895.0
38,0,106,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,9095.0
39,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,8845.0
40,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,10295.0
41,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.00,101,5800,24,28,12945.0
42,1,107,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.10,100,5500,25,31,10345.0
43,0,NaN,isuzu,gas,std,four,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.50,78,4800,24,29,6785.0
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,NaN
46,2,NaN,isuzu,gas,std,two,hatchback,rwd,front,96.0,...,119,spfi,3.43,3.23,9.20,90,5000,24,29,11048.0
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,32250.0
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,35550.0
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.50,262,5000,13,17,36000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0,91,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,27,32,8778.0
156,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,6938.0
157,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,7198.0
158,0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,34,36,7898.0
159,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,38,47,7788.0
160,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,38,47,7738.0
161,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,28,34,8358.0
162,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,28,34,9258.0
163,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70,4800,29,34,8058.0
164,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70,4800,29,34,8238.0
165,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112,6600,26,29,9298.0
166,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112,6600,26,29,9538.0
167,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,8449.0
168,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,9639.0
169,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,9989.0
170,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,11199.0
171,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,11549.0
172,2,134,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,17669.0
173,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,29,34,8948.0
174,-1,65,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.50,73,4500,30,33,10698.0
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,9988.0
176,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,10898.0
177,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,11248.0
178,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,20,24,16558.0
179,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,19,24,15998.0
180,-1,90,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.20,156,5200,20,24,15690.0
181,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.20,156,5200,19,24,15750.0
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7775.0
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,7975.0
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7995.0
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,8195.0
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,8495.0
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,68,4500,37,42,9495.0
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.00,100,5500,26,32,9995.0
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90,5500,24,29,11595.0
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90,5500,24,29,9980.0
191,0,NaN,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.50,110,5500,19,24,13295.0
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.00,68,4500,33,38,13845.0
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.00,88,5500,25,31,12290.0
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,12940.0
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,13415.0
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,15985.0
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,16515.0
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18420.0
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18950.0
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.00,106,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625.0

In [22]:
df1['price'].head()

0    13495.0
1    16500.0
2    16500.0
3    13950.0
4    17450.0
Name: price, dtype: float64

In [23]:
df1['price'].dtype

dtype('float64')

In [24]:
df1.describe()

,symboling,wheel-base,length,width,height,curb_weight,engine_size,compression_ratio,city_mpg,highway_mpg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220,13207.129353
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443,7947.066342
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000,7775.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000,10295.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000,16500.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000,45400.000000

### Before scaling the feature into z-score, I realized I should convert the features properly into numeric, if applicable, first.

### My created method 3: finding informative columns that has more than 1 unique values.

In [25]:
# My created method 3: finding informative columns that has more than 1 unique values.

def informative_cols(df):
    informative = [column for column in df.columns 
                       if len(df[column].unique()) > 1]
    
    return df[informative]

In [26]:
informative_cols(df1)

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500.0
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950.0
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,15250.0
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110,5500,19,25,18920.0
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.30,140,5500,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16430.0
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16925.0
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,20970.0
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121,4250,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121,4250,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182,5400,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182,5400,15,20,36880.0
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151.0
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295.0
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575.0
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572.0
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377.0
23,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,7957.0
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229.0
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692.0
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,7609.0
27,1,148,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102,5500,24,30,8558.0
28,-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88,5000,24,30,8921.0
29,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.00,145,5000,19,24,12964.0
30,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.60,58,4800,49,54,6479.0
31,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76,6000,31,38,6855.0
32,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.10,60,5500,38,42,5399.0
33,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,6529.0
34,1,101,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7129.0
35,0,110,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.20,76,6000,30,34,7295.0
36,0,78,honda,gas,std,four,wagon,fwd,front,96.5,...,92,1bbl,2.92,3.41,9.20,76,6000,30,34,7295.0
37,0,106,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,7895.0
38,0,106,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,9095.0
39,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,8845.0
40,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86,5800,27,33,10295.0
41,0,85,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.00,101,5800,24,28,12945.0
42,1,107,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.10,100,5500,25,31,10345.0
43,0,NaN,isuzu,gas,std,four,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.50,78,4800,24,29,6785.0
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,NaN
46,2,NaN,isuzu,gas,std,two,hatchback,rwd,front,96.0,...,119,spfi,3.43,3.23,9.20,90,5000,24,29,11048.0
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,32250.0
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176,4750,15,19,35550.0
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.50,262,5000,13,17,36000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0,91,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62,4800,27,32,8778.0
156,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,6938.0
157,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,30,37,7198.0
158,0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,34,36,7898.0
159,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56,4500,38,47,7788.0
160,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,38,47,7738.0
161,0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,28,34,8358.0
162,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70,4800,28,34,9258.0
163,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70,4800,29,34,8058.0
164,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70,4800,29,34,8238.0
165,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112,6600,26,29,9298.0
166,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112,6600,26,29,9538.0
167,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,8449.0
168,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,9639.0
169,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,9989.0
170,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,11199.0
171,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,11549.0
172,2,134,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116,4800,24,30,17669.0
173,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,29,34,8948.0
174,-1,65,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.50,73,4500,30,33,10698.0
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,9988.0
176,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,10898.0
177,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92,4200,27,32,11248.0
178,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,20,24,16558.0
179,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161,5200,19,24,15998.0
180,-1,90,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.20,156,5200,20,24,15690.0
181,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.20,156,5200,19,24,15750.0
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7775.0
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,7975.0
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52,4800,37,46,7995.0
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,8195.0
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85,5250,27,34,8495.0
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,68,4500,37,42,9495.0
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.00,100,5500,26,32,9995.0
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90,5500,24,29,11595.0
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90,5500,24,29,9980.0
191,0,NaN,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.50,110,5500,19,24,13295.0
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.00,68,4500,33,38,13845.0
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.00,88,5500,25,31,12290.0
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,12940.0
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,13415.0
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,15985.0
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114,5400,24,28,16515.0
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18420.0
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162,5100,17,22,18950.0
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,23,28,16845.0
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.70,160,5300,19,25,19045.0
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.80,134,5500,18,23,21485.0
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.00,106,4800,26,27,22470.0
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114,5400,19,25,22625.0

In [27]:
len(informative_cols(df1).columns)

26

In [28]:
columns_informative = [column for column in df1.columns if len(df1[column].unique()) > 1]
print(columns_informative)
len(columns_informative)

['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style', 'drive_wheels', 'engine_location', 'wheel-base', 'length', 'width', 'height', 'curb_weight', 'engine_type', 'num_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke', 'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg', 'highway_mpg', 'price']

26

### All of the columns in my dataset df1 have more than one unique values, which are informative.

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null object
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_of_doors         203 non-null object
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_of_cylinders     205 non-null object
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null object
stroke               201 non-null object
compression_ratio    205 non-null float64
horsepower           203 non-null object
peak_rpm             203 non-null object
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null float64
dtypes: float64(6), int64(5), object(15)
memory usage: 41.8+ KB

### Impute Means

We should impute the means only after properly coercing columns into the correct format.

In [30]:
sorted_nas.head(10)

normalized_losses    41
price                 4
stroke                4
bore                  4
peak_rpm              2
horsepower            2
num_of_doors          2
length                0
make                  0
fuel_type             0
dtype: int64

In [31]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null object
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_of_doors         203 non-null object
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_of_cylinders     205 non-null object
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null object
stroke               201 non-null object
compression_ratio    205 non-null float64
horsepower           203 non-null object
peak_rpm             203 non-null object
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null float64
dtypes: float64(6), int64(5), object(15)
memory usage: 41.8+ KB

### To impute the NaNs into mean value, I decided to write a method to find the numeric columns.

### My created method 4: Finding the numeric columns that has NaNs.

In [32]:
# My created method 4: Finding the numeric columns that has nas.

import pandas as pd

def numeric_nas_columns(df):
    numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
    df_numeric = df[numeric_columns]
    numeric_nas_sorted = df_numeric.isnull().sum().sort_values(ascending=False)
    return numeric_nas_sorted

In [33]:
numeric_nas_columns(df1)

price                4
highway_mpg          0
city_mpg             0
compression_ratio    0
engine_size          0
curb_weight          0
height               0
width                0
length               0
wheel-base           0
symboling            0
dtype: int64

In [34]:
numeric_columns = df1.select_dtypes(include=['float64', 'int64']).columns
print(numeric_columns)
df1[numeric_columns].T

Index(['symboling', 'wheel-base', 'length', 'width', 'height', 'curb_weight',
       'engine_size', 'compression_ratio', 'city_mpg', 'highway_mpg', 'price'],
      dtype='object')

,0,1,2,3,4,5,6,7,8,9,...,195,196,197,198,199,200,201,202,203,204
symboling,3.0,3.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,0.0,...,-1.0,-2.0,-1.0,-2.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,99.5,...,104.3,104.3,104.3,104.3,104.3,109.1,109.1,109.1,109.1,109.1
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,178.2,...,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,67.9,...,67.2,67.2,67.2,67.2,67.2,68.9,68.8,68.9,68.9,68.9
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,52.0,...,57.5,56.2,57.5,56.2,57.5,55.5,55.5,55.5,55.5,55.5
curb_weight,2548.0,2548.0,2823.0,2337.0,2824.0,2507.0,2844.0,2954.0,3086.0,3053.0,...,3034.0,2935.0,3042.0,3045.0,3157.0,2952.0,3049.0,3012.0,3217.0,3062.0
engine_size,130.0,130.0,152.0,109.0,136.0,136.0,136.0,136.0,131.0,131.0,...,141.0,141.0,141.0,130.0,130.0,141.0,141.0,173.0,145.0,141.0
compression_ratio,9.0,9.0,9.0,10.0,8.0,8.5,8.5,8.5,8.3,7.0,...,9.5,9.5,9.5,7.5,7.5,9.5,8.7,8.8,23.0,9.5
city_mpg,21.0,21.0,19.0,24.0,18.0,19.0,19.0,19.0,17.0,16.0,...,23.0,24.0,24.0,17.0,17.0,23.0,19.0,18.0,26.0,19.0
highway_mpg,27.0,27.0,26.0,30.0,22.0,25.0,25.0,25.0,20.0,22.0,...,28.0,28.0,28.0,22.0,22.0,28.0,25.0,23.0,27.0,25.0
price,13495.0,16500.0,16500.0,13950.0,17450.0,15250.0,17710.0,18920.0,23875.0,NaN,...,13415.0,15985.0,16515.0,18420.0,18950.0,16845.0,19045.0,21485.0,22470.0,22625.0

In [35]:
def impute_means_on_nas(df):
     copied_df = df.copy()
     mean_series = df.mean(axis = 0, skipna = True, numeric_only = True)
     values = dict(zip(mean_series.index, mean_series.values))
     copied_df.fillna(value = values)

### I realized this step such as finding the numeric columns that has Nas and imputing the Nas into mean value should be done after I convert all the applicable features into numeric first, like I mentioned above that I should scale the features into z-score after I properly convert the applicable features into numeric data type first. In addition, imputation should be conducted BEFORE I scale the features into z-score to find outliers, and then conduct RFECV & RFE.

### So far, I checked the columns that has NaN, and I converted 'price' column into numeric, but I should convert other applicable columns into numeric data type before I move forward to the next steps.

### To be able to see and check the columns and the datatype at the same time, I decided to write a method to concatenate the first nine rows of datafrmae and the datatype of each column as below:

### My created method 5: concatenating the first nine rows of dataframe and datatype of each column

In [36]:
# My created method 5: concatenating the first nine rows of dataframe and datatype of each column.

import pandas as pd

def concat_datatype(df):
    a = df.head(9).T
    b = pd.DataFrame(df.dtypes)
    return pd.concat([a,b], axis=1)

In [37]:
concat_datatype(df1)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,object
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,object
aspiration,std,std,std,std,std,std,std,std,turbo,object
num_of_doors,two,two,two,four,four,two,four,four,four,object
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
engine_location,front,front,front,front,front,front,front,front,front,object
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
num_of_cylinders,four,four,six,four,five,five,five,five,five,object
engine_size,130,130,152,109,136,136,136,136,131,int64
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,object
stroke,2.68,2.68,3.47,3.40,3.40,3.40,3.40,3.40,3.40,object
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,object
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,object
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64

### By looking at the dataframe that I created by concatenating the first nine rows and the datatype of each feature above, here are the list of potential feature engineering that I need to do on the applicable features:<br>

1. symboling: no change.<br>
2. normalized_losses: convert into numeric datatype.<br>
#### 3. make: convert text to booleans or get dummies to meet the basic requirements<br>
#### 4. fuel_type: convert text to booleans or get dummies to meet the basic requirements<br>
#### 5. aspiration: convert text to booleans or get dummies to meet the basic requirements<br>
#### 6. num_of_doors: convert "almost" numbers to numbers to meet the DATA MUNGING requirements for at least three columns.<br>
#### 7. body_style: convert columns that beging as type "object" into categories to meet the DATA MUNGING requirements for at least three columns.<br>
#### 8. drive_wheels: convert text to booleans or get dummies to meet the basic requirements<br>
#### 9. engine_location: convert text to booleans or get dummies to meet the basic requirements<br>
10.wheel_base: no change.<br>
11.length: no change.<br>
12.width: no change.<br>
13.height: no change.<br>
14.curb_weight:no change.<br>
#### 15.engine_type: convert columns that begin as type "object" into categories to meet the DATA MUNGING munging requirements for at least three columns.<br>
#### 16. num_of_cylinders: convert "almost" numbers to numbers to meet the DATA MUNGING requirements for at least three columns.<br>
17.engine_size: no change.<br>
#### 18.fuel_system: convert columns that begin as type "object" into categories to meet the DATA MUNGING requirements for at least three columns.<br>
19.bore: convert "object" into numeric datatype.<br>
20.stroke: convert "object" into numeric datatype.<br>
21.compression_ratio: no change.<br>
22.horsepower: convert "object" into numeric datatype.<br>
23.peak_rpm: convert "object" into numeric datatype.<br>
24.city_mpg: no change.<br>
25.highway_mpg: no change.<br>
26.price: I arleady changed the "object"datatype into numeric, previously.

### Below, I categorized how I will potentially proceed feature engineering to meet all the feature coercion and generation requirements.

- (1) Converting "object" into numeric datatype<br>
2.normalized_losses: convert into numeric datatype.<br>
19.bore: convert "object" into numeric datatype.<br>
20.stroke: convert "object" into numeric datatype.<br>
22.horsepower: convert "object" into numeric datatype.<br>
23.peak_rpm: convert "object" into numeric datatype.<br>
26.price:I already changed the "object" into numeric datatype.<br>
<br>
- (2) Basic Requirements<br>
3.make: convert text to booleans or get dummies to meet the basic requirements<br>
4.fuel_type: convert text to booleans or get dummies to meet the basic requirements<br>
5.aspiration: convert text to booleans or get dummies to meet the basic requirements<br>
8.drive_wheels: convert text to booleans or get dummies to meet the basic requirements<br>
9.engine_location: convert text to booleans or get dummies to meet the basic requirements<br>
<br>
- (3) Data Munging Requirements for at least three columns<br>
6.num_of_doors: convert "almost" numbers to numbers to meet the DATA MUNGING requirements for at least three columns.<br>
16.num_of_cylinders: convert "almost" numbers to numbers to meet the DATA MUNGING requirements for at least three columns.<br>
7.body_style: convert columns that beging as type "object" into categories to meet the DATA MUNGING requirements for at least three columns.<br>
15.engine_type: convert columns that begin as type "object" into categories to meet the DATA MUNGING munging requirements for at least three columns.<br>
18.fuel_system: convert columns that begin as type "object" into categories to meet the DATA MUNGING requirements for at least three columns.<br>
<br>
- (4) Clean Code Requirements - write at least three methods><br>
I already stated "my created methods" above, each time I wrote the method, respecitely.

### (1) Converting "object" into numeric datatype

### I decided to write a method to convert multiple columns into numeric data type as below.

### My created method 6: converting multiple columns into numeric data type.

In [38]:
# My created method 6: converting multiple columns into numeric data type.

import pandas as pd

def convert_multiple_numeric(df, column_list):
    for column in column_list:
        df[column] = df[column].apply(pd.to_numeric, errors= 'coerce')
    return df

In [39]:
convert_multiple_numeric(df1, ['normalized_losses', 'bore', 'stroke',
                               'horsepower', 'peak_rpm', 'price'])

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel-base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.00,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.00,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.00,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.00,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,15250.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,25,18920.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.30,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.00,160.0,5500.0,16,22,NaN
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16430.0
11,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.80,101.0,5800.0,23,29,16925.0
12,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,20970.0
13,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.00,121.0,4250.0,20,25,24565.0
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,30760.0
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,16,22,41315.0
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.00,182.0,5400.0,15,20,36880.0
18,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48.0,5100.0,47,53,5151.0
19,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6295.0
20,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,6575.0
21,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68.0,5500.0,37,41,5572.0
22,1,118.0,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6377.0
23,1,118.0,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,7957.0
24,1,148.0,dodge,gas,std,four,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6229.0
25,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,6692.0
26,1,148.0,dodge,gas,std,four,sedan,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68.0,5500.0,31,38,7609.0
27,1,148.0,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,...,98,mpfi,3.03,3.39,7.60,102.0,5500.0,24,30,8558.0
28,-1,110.0,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.50,88.0,5000.0,24,30,8921.0
29,3,145.0,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,156,mfi,3.60,3.90,7.00,145.0,5000.0,19,24,12964.0
30,2,137.0,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.60,58.0,4800.0,49,54,6479.0
31,2,137.0,honda,gas,std,two,hatchback,fwd,front,86.6,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,31,38,6855.0
32,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,79,1bbl,2.91,3.07,10.10,60.0,5500.0,38,42,5399.0
33,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,6529.0
34,1,101.0,honda,gas,std,two,hatchback,fwd,front,93.7,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,7129.0
35,0,110.0,honda,gas,std,four,sedan,fwd,front,96.5,...,92,1bbl,2.91,3.41,9.20,76.0,6000.0,30,34,7295.0
36,0,78.0,honda,gas,std,four,wagon,fwd,front,96.5,...,92,1bbl,2.92,3.41,9.20,76.0,6000.0,30,34,7295.0
37,0,106.0,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,7895.0
38,0,106.0,honda,gas,std,two,hatchback,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,9095.0
39,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,8845.0
40,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,1bbl,3.15,3.58,9.00,86.0,5800.0,27,33,10295.0
41,0,85.0,honda,gas,std,four,sedan,fwd,front,96.5,...,110,mpfi,3.15,3.58,9.00,101.0,5800.0,24,28,12945.0
42,1,107.0,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.10,100.0,5500.0,25,31,10345.0
43,0,NaN,isuzu,gas,std,four,sedan,rwd,front,94.3,...,111,2bbl,3.31,3.23,8.50,78.0,4800.0,24,29,6785.0
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70.0,5400.0,38,43,NaN
46,2,NaN,isuzu,gas,std,two,hatchback,rwd,front,96.0,...,119,spfi,3.43,3.23,9.20,90.0,5000.0,24,29,11048.0
47,0,145.0,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176.0,4750.0,15,19,32250.0
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.10,176.0,4750.0,15,19,35550.0
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.50,262.0,5000.0,13,17,36000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0,91.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.00,62.0,4800.0,27,32,8778.0
156,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,30,37,6938.0
157,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,30,37,7198.0
158,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56.0,4500.0,34,36,7898.0
159,0,91.0,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.50,56.0,4500.0,38,47,7788.0
160,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,38,47,7738.0
161,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,28,34,8358.0
162,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,28,34,9258.0
163,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,29,34,8058.0
164,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.00,70.0,4800.0,29,34,8238.0
165,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112.0,6600.0,26,29,9298.0
166,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.40,112.0,6600.0,26,29,9538.0
167,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,8449.0
168,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,9639.0
169,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,9989.0
170,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,11199.0
171,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,11549.0
172,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.30,116.0,4800.0,24,30,17669.0
173,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,29,34,8948.0
174,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.50,73.0,4500.0,30,33,10698.0
175,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,9988.0
176,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,10898.0
177,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.70,92.0,4200.0,27,32,11248.0
178,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161.0,5200.0,20,24,16558.0
179,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.30,161.0,5200.0,19,24,15998.0
180,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.20,156.0,5200.0,20,24,15690.0
181,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.20,156.0,5200.0,19,24,15750.0
182,2,122.0,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52.0,4800.0,37,46,7775.0
183,2,122.0,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,7975.0
184,2,94.0,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,52.0,4800.0,37,46,7995.0
185,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,8195.0
186,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.00,85.0,5250.0,27,34,8495.0
187,2,94.0,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.00,68.0,4500.0,37,42,9495.0
188,2,94.0,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.00,100.0,5500.0,26,32,9995.0
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90.0,5500.0,24,29,11595.0
190,3,256.0,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.50,90.0,5500.0,24,29,9980.0
191,0,NaN,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.50,110.0,5500.0,19,24,13295.0
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.00,68.0,4500.0,33,38,13845.0
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.00,88.0,5500.0,25,31,12290.0
194,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,12940.0
195,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,13415.0
196,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,24,28,15985.0
197,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,24,28,16515.0
198,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162.0,5100.0,17,22,18420.0
199,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.50,162.0,5100.0,17,22,18950.0
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.70,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.80,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.00,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.50,114.0,5400.0,19,25,22625.0

In [40]:
df1['horsepower'].dtype

dtype('float64')

In [41]:
df1.describe()

,symboling,normalized_losses,wheel-base,length,width,height,curb_weight,engine_size,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
count,205.000000,164.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,201.000000,201.000000,205.000000,203.000000,203.000000,205.000000,205.000000,201.000000
mean,0.834146,122.000000,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329751,3.255423,10.142537,104.256158,5125.369458,25.219512,30.751220,13207.129353
std,1.245307,35.442168,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.273539,0.316717,3.972040,39.714369,479.334560,6.542142,6.886443,7947.066342
min,-2.000000,65.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,94.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000
50%,1.000000,115.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,150.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.590000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000
max,3.000000,256.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [42]:
concat_datatype(df1)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,float64
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,object
aspiration,std,std,std,std,std,std,std,std,turbo,object
num_of_doors,two,two,two,four,four,two,four,four,four,object
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
engine_location,front,front,front,front,front,front,front,front,front,object
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
num_of_cylinders,four,four,six,four,five,five,five,five,five,object
engine_size,130,130,152,109,136,136,136,136,131,int64
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,float64
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,float64
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,float64
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64

### (2) Converting almost numbers into number

In [43]:
df1['num_of_cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [44]:
df1['num_of_doors'].unique()

array(['two', 'four', nan], dtype=object)

In [45]:
mapping1 = {'four': 4, 'six': 6, 'five': 5, 'three': 3, 'twelve' :12, 'two': 2, 'eight': 8}
import numpy as np

# My created method : replacing almost number into number

def replaced_number(df):
    df = df.replace(mapping1, inplace = True)
    return df

In [46]:
df1['num_of_cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [47]:
df1['num_of_doors'].unique()

array(['two', 'four', nan], dtype=object)

In [48]:
replaced_number(df1)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null float64
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_of_doors         203 non-null float64
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_of_cylinders     205 non-null int64
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null float64
stroke               201 non-null float64
compression_ratio    205 non-null float64
horsepower           203 non-null float64
peak_rpm             203 non-null float64
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null float64
dtypes: float64(12), int64(6), object(8)
memory usage: 41.8+ KB

In [49]:
df1[['num_of_doors', 'num_of_cylinders']].head()

   num_of_doors  num_of_cylinders
0           2.0                 4
1           2.0                 4
2           2.0                 6
3           4.0                 4
4           4.0                 5

In [50]:
def find_object_features(df):
    return list(df.dtypes[df.dtypes == 'object'].index)

In [51]:
find_object_features(df1)

['make',
 'fuel_type',
 'aspiration',
 'body_style',
 'drive_wheels',
 'engine_location',
 'engine_type',
 'fuel_system']

### (3) Converting text to booleans or get dummies: Now, I have total 8 'object' or 'text' features to engineer further.<br>

In [52]:
concat_datatype(df1[find_object_features(df1)])

,0,1,2,3,4,5,6,7,8,0
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,object
aspiration,std,std,std,std,std,std,std,std,turbo,object
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
engine_location,front,front,front,front,front,front,front,front,front,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

### I decided to make a method to find unique values of each column and return the list of them.

### My created method 7: finding unique values of multiple columns.

In [53]:
# My created method 7: finding unique values of multiple columns.

import numpy as np

def finding_unique(df, column_list):
    if not isinstance(column_list, list):
        column_list = [column_list]
    unique_value = []
    for column in column_list:
        unique_values = df[column].unique()
        column_name = column
        unique_value.append(column_name)
        unique_value.append(unique_values)
        uniques = np.array(unique_value)
    return np.array([unique for unique in uniques])

In [54]:
finding_unique(df1, find_object_features(df1))

array(['make',
       array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object),
       'fuel_type', array(['gas', 'diesel'], dtype=object), 'aspiration',
       array(['std', 'turbo'], dtype=object), 'body_style',
       array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object),
       'drive_wheels', array(['rwd', 'fwd', '4wd'], dtype=object),
       'engine_location', array(['front', 'rear'], dtype=object),
       'engine_type',
       array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object),
       'fuel_system',
       array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)], dtype=object)

### My created method 8: Finding booleans

In [55]:
#finding booleans that has only 2 values to convert to booleans by mapping.
# I modified the method "find_booleans" into simpler way as below.
# My modified method : finding booleans

import numpy as np

def find_booleans(df):   
    columns = df.columns  
    boolean_columns = np.array([column for column in columns if len(df[column].value_counts()) == 2])
    boolean_values = np.array([df[column].unique() for column in boolean_columns])
    columns_and_values = np.stack((boolean_columns, boolean_values)).T
    return columns_and_values

In [56]:
find_booleans(df1)

array([['fuel_type', array(['gas', 'diesel'], dtype=object)],
       ['aspiration', array(['std', 'turbo'], dtype=object)],
       ['num_of_doors', array([ 2.,  4., nan])],
       ['engine_location', array(['front', 'rear'], dtype=object)]],
      dtype=object)

### Based on above, for the features, which have more than two values, I will get dummies after I categorize the low frequency values into 'other'. For the other three 'object' columns such as 'fuel_type', 'aspiration', 'engine_location', which has two values in respective feature, I will convert text to booleans. 'num_of_doors' features is already converted into numeric, as shown in the previous step.

In [57]:
def find_object_features(df):
    return list(df.dtypes[df.dtypes == 'object'].index)

In [58]:
find_object_features(df1)

['make',
 'fuel_type',
 'aspiration',
 'body_style',
 'drive_wheels',
 'engine_location',
 'engine_type',
 'fuel_system']

### I decided to make a method to return the unique values for the 'object' features

In [59]:
# My created method : finding unique values for the 'object featrues'

def find_object_feature_values(df):
    object_features = find_object_features(df)
    unique_list = []
    for object in object_features:
        unique_value = df[object].unique()
        unique_list.append(object)
        unique_list.append(unique_value)
        uniques = np.array(unique_list)
    return np.array([unique for unique in uniques])

In [60]:
find_object_feature_values(df1)

array(['make',
       array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object),
       'fuel_type', array(['gas', 'diesel'], dtype=object), 'aspiration',
       array(['std', 'turbo'], dtype=object), 'body_style',
       array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object),
       'drive_wheels', array(['rwd', 'fwd', '4wd'], dtype=object),
       'engine_location', array(['front', 'rear'], dtype=object),
       'engine_type',
       array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object),
       'fuel_system',
       array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)], dtype=object)

### Based on the output above, I found that thre is no "boolean" features that has 't' or 'f' value, so I decided to find the "almost_boolean" features.

In [61]:
#checking the object features for the further feature engineering
find_object_features(df1)

['make',
 'fuel_type',
 'aspiration',
 'body_style',
 'drive_wheels',
 'engine_location',
 'engine_type',
 'fuel_system']

In [62]:
concat_datatype(df1[find_object_features(df1)])

,0,1,2,3,4,5,6,7,8,0
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,object
aspiration,std,std,std,std,std,std,std,std,turbo,object
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
engine_location,front,front,front,front,front,front,front,front,front,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

### Finding almost binary features: I decided to find almost binary feature among these object features. After that, I will convert the remaining features into categorical including 'other' value and then get dummies.

### My created method 9: I modified 'summarize_counts(df)' method to return the top values in descending order of frequencies for each 'object' feature that I have.

In [63]:
# My created method : Returning the top values in descending order of frequencies for each 'object' feature
    
def summarize_counts(df):
    object_features = find_object_features(df)
    frequencies = np.array([df[column].value_counts(normalize=True).values[0] for column in object_features]).reshape(-1, 1)
    columns = np.array(object_features).reshape(-1, 1)
    top_values = np.array([df[column].value_counts(normalize=True).index[0] for column in object_features]).reshape(-1, 1)
    summarize = np.hstack((columns, frequencies, top_values)) 
    return summarize[summarize[:, 1].argsort()[::-1]]

In [64]:
summarize_counts(df1)

array([['engine_location', '0.9853658536585366', 'front'],
       ['fuel_type', '0.9024390243902439', 'gas'],
       ['aspiration', '0.8195121951219512', 'std'],
       ['engine_type', '0.7219512195121951', 'ohc'],
       ['drive_wheels', '0.5853658536585366', 'fwd'],
       ['body_style', '0.4682926829268293', 'sedan'],
       ['fuel_system', '0.4585365853658537', 'mpfi'],
       ['make', '0.15609756097560976', 'toyota']], dtype='<U32')

In [65]:
summarize_counts(df1)[:, 1][0].dtype

dtype('<U18')

In [66]:
concat_datatype(df1[find_object_features(df1)])

,0,1,2,3,4,5,6,7,8,0
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
fuel_type,gas,gas,gas,gas,gas,gas,gas,gas,gas,object
aspiration,std,std,std,std,std,std,std,std,turbo,object
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
engine_location,front,front,front,front,front,front,front,front,front,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

In [67]:
find_booleans(df1)

array([['fuel_type', array(['gas', 'diesel'], dtype=object)],
       ['aspiration', array(['std', 'turbo'], dtype=object)],
       ['num_of_doors', array([ 2.,  4., nan])],
       ['engine_location', array(['front', 'rear'], dtype=object)]],
      dtype=object)

### I decided to modify "almost_binary" method to find the almost_binary feature using threshold 0.80, as the aspiration has the top value at 81.95% frequency, because I want to convert all the 'object' features that have only 2 values into boolean.

### My created method 10: finding the almost binary features to convert into boolean.

In [68]:
# My created method : finding the almost binary features that has threshold of 0.80 frequency.

def almost_binary(df, threshold = .80 ):
    return np.array([np.array([cat, top]) for cat, freq, top in summarize_counts(df) if 1.0 > float(freq) > threshold])

In [69]:
almost_binary(df1)

array([['engine_location', 'front'],
       ['fuel_type', 'gas'],
       ['aspiration', 'std']], dtype='<U15')

In [70]:
def remove_punctuation(string):
    return string.strip().lower().replace(' ', '_').replace('(', '').replace(')', '').replace(',', '')

In [71]:
def matrix_new_features(df):
    bin_feats = almost_binary(df)
    new_bin_feats = np.array(['{column}_is_{top}'.format(column = column, top = remove_punctuation(top)) for column, top in bin_feats])
    return np.hstack((bin_feats[:, 0].reshape(-1, 1), bin_feats[:, 1].reshape(-1, 1), new_bin_feats.reshape(-1, 1)))

In [72]:
matrix_new_features(df1)

array([['engine_location', 'front', 'engine_location_is_front'],
       ['fuel_type', 'gas', 'fuel_type_is_gas'],
       ['aspiration', 'std', 'aspiration_is_std']], dtype='<U24')

In [73]:
def booleans_without_top_values(df, not_values_list):
    potential_new_features = matrix_new_features(df)
    not_tf = ~np.isin(potential_new_features[:, 1], not_values_list)
    return potential_new_features[not_tf]

In [74]:
booleans_without_top_values(df1, ['t', 'f'])

array([['engine_location', 'front', 'engine_location_is_front'],
       ['fuel_type', 'gas', 'fuel_type_is_gas'],
       ['aspiration', 'std', 'aspiration_is_std']], dtype='<U24')

In [75]:
def almost_to_boolean(df):
    columns_to_replace = matrix_new_features(df)[:, 0]
    values_to_replace = matrix_new_features(df)[:, 1]
    new_column_names = matrix_new_features(df)[:, 2]
    to_replace_df = pd.DataFrame({})
    for column, value, new_name in zip(columns_to_replace, values_to_replace, new_column_names):
        bool_column = np.where(df[column] == value, 1, 0)
        to_replace_df[new_name] = bool_column
    return to_replace_df

In [76]:
almost_to_boolean(df1).head(10)

   engine_location_is_front  fuel_type_is_gas  aspiration_is_std
0                         1                 1                  1
1                         1                 1                  1
2                         1                 1                  1
3                         1                 1                  1
4                         1                 1                  1
5                         1                 1                  1
6                         1                 1                  1
7                         1                 1                  1
8                         1                 1                  0
9                         1                 1                  0

### My created method 11: converting the text columns into boolean by replacing them in the dataframe.

In [77]:
# My created method : replacing the original columns with boolean columns 

def replace_booleans(df, column_list):
    pruned_df = df.drop(column_list, axis=1)
    df = pd.concat([pruned_df, almost_to_boolean(df)], axis=1)
    return df

In [78]:
df2 = replace_booleans(df1, matrix_new_features(df1)[:, 0])
df2.head().T

                                    0            1            2      3      4
symboling                           3            3            1      2      2
normalized_losses                 NaN          NaN          NaN    164    164
make                      alfa-romero  alfa-romero  alfa-romero   audi   audi
num_of_doors                        2            2            2      4      4
body_style                convertible  convertible    hatchback  sedan  sedan
drive_wheels                      rwd          rwd          rwd    fwd    4wd
wheel-base                       88.6         88.6         94.5   99.8   99.4
length                          168.8        168.8        171.2  176.6  176.6
width                            64.1         64.1         65.5   66.2   66.4
height                           48.8         48.8         52.4   54.3   54.3
curb_weight                      2548         2548         2823   2337   2824
engine_type                      dohc         dohc         ohcv    ohc    ohc
num_of_cylinders                    4            4            6      4      5
engine_size                       130          130          152    109    136
fuel_system                      mpfi         mpfi         mpfi   mpfi   mpfi
bore                             3.47         3.47         2.68   3.19   3.19
stroke                           2.68         2.68         3.47    3.4    3.4
compression_ratio                   9            9            9     10      8
horsepower                        111          111          154    102    115
peak_rpm                         5000         5000         5000   5500   5500
city_mpg                           21           21           19     24     18
highway_mpg                        27           27           26     30     22
price                           13495        16500        16500  13950  17450
engine_location_is_front            1            1            1      1      1
fuel_type_is_gas                    1            1            1      1      1
aspiration_is_std                   1            1            1      1      1

In [79]:
concat_datatype(df2)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,float64
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,object
num_of_doors,2,2,2,4,4,2,4,4,4,float64
body_style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,object
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
num_of_cylinders,4,4,6,4,5,5,5,5,5,int64
engine_size,130,130,152,109,136,136,136,136,131,int64
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,float64
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,float64
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,float64
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64
engine_location_is_front,1,1,1,1,1,1,1,1,1,int32
fuel_type_is_gas,1,1,1,1,1,1,1,1,1,int32
aspiration_is_std,1,1,1,1,1,1,1,1,0,int32

In [80]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling                   205 non-null int64
normalized_losses           164 non-null float64
make                        205 non-null object
num_of_doors                203 non-null float64
body_style                  205 non-null object
drive_wheels                205 non-null object
wheel-base                  205 non-null float64
length                      205 non-null float64
width                       205 non-null float64
height                      205 non-null float64
curb_weight                 205 non-null int64
engine_type                 205 non-null object
num_of_cylinders            205 non-null int64
engine_size                 205 non-null int64
fuel_system                 205 non-null object
bore                        201 non-null float64
stroke                      201 non-null float64
compression_ratio           205 non-null float64
horsepower                  203 non-null float64
peak_rpm                    203 non-null float64
city_mpg                    205 non-null int64
highway_mpg                 205 non-null int64
price                       201 non-null float64
engine_location_is_front    205 non-null int32
fuel_type_is_gas            205 non-null int32
aspiration_is_std           205 non-null int32
dtypes: float64(12), int32(3), int64(6), object(5)
memory usage: 39.4+ KB

In [81]:
find_object_features(df2)

['make', 'body_style', 'drive_wheels', 'engine_type', 'fuel_system']

### So far, I have engineered features as shown above, and now I have only five object features left. I will convert this "object" into "categorical" by including "other" value for the less frequent values, and then I will get dummies.

### (4) Converting "object" into "categorical" , and then get dummies

In [82]:
# My created method 7: finding unique values of multiple columns.

import numpy as np

def finding_unique(df, column_list):
    if not isinstance(column_list, list):
        column_list = [column_list]
    unique_value = []
    for column in column_list:
        unique_values = df[column].unique()
        column_name = column
        unique_value.append(column_name)
        unique_value.append(unique_values)
        uniques = np.array(unique_value)
    return np.array([unique for unique in uniques])

In [83]:
finding_unique(df2, find_object_features(df2))

array(['make',
       array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object),
       'body_style',
       array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object),
       'drive_wheels', array(['rwd', 'fwd', '4wd'], dtype=object),
       'engine_type',
       array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object),
       'fuel_system',
       array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)], dtype=object)

In [84]:
find_object_features(df2)

['make', 'body_style', 'drive_wheels', 'engine_type', 'fuel_system']

In [85]:
def percentage_unique(df_series):
    series_filled = df_series.dropna()
    return len(series_filled.unique())/len(series_filled)

In [86]:
df1['body_style'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [87]:
percentage_unique(df2['make'])

0.1073170731707317

In [88]:
percentage_unique(df2.fuel_system)

0.03902439024390244

In [89]:
# I modified the "find_categorical" method as below, using find_object_features(df) instead of df.columns to exclude numeric.

def find_categorical(df, threshold = .5):
    categorical_df = pd.DataFrame({})
    for column in find_object_features(df):
        if percentage_unique(df[column]) < threshold:
            categorical_df[column] = df[column]
    return categorical_df

In [90]:
find_categorical(df2).head()

          make   body_style drive_wheels engine_type fuel_system
0  alfa-romero  convertible          rwd        dohc        mpfi
1  alfa-romero  convertible          rwd        dohc        mpfi
2  alfa-romero    hatchback          rwd        ohcv        mpfi
3         audi        sedan          fwd         ohc        mpfi
4         audi        sedan          4wd         ohc        mpfi

In [91]:
# My created method : Returning the top values in descending order of frequencies for each 'object' feature
    
def summarize_counts(df):
    object_features = find_object_features(df)
    frequencies = np.array([df[column].value_counts(normalize=True).values[0] for column in object_features]).reshape(-1, 1)
    columns = np.array(object_features).reshape(-1, 1)
    top_values = np.array([df[column].value_counts(normalize=True).index[0] for column in object_features]).reshape(-1, 1)
    summarize = np.hstack((columns, frequencies, top_values)) 
    return summarize[summarize[:, 1].argsort()[::-1]]

In [92]:
summarize_counts(df2)

array([['engine_type', '0.7219512195121951', 'ohc'],
       ['drive_wheels', '0.5853658536585366', 'fwd'],
       ['body_style', '0.4682926829268293', 'sedan'],
       ['fuel_system', '0.4585365853658537', 'mpfi'],
       ['make', '0.15609756097560976', 'toyota']], dtype='<U32')

### My created method 12: returning the potential "categorical" columns

In [93]:
def selected_summaries(df, not_values = [], lower_bound = .1, upper_bound = 1):
    potential_cols = np.array([np.array([cat, freq, top]) for cat, freq, top in summarize_counts(df) 
                               if lower_bound < float(freq) < upper_bound])
    not_tf = ~np.isin(summarize_counts(df)[: ,2], not_values)
    return potential_cols[not_tf]

In [94]:
selected = selected_summaries(df2, not_values = ['t', 'f'], upper_bound = .90)
selected

array([['engine_type', '0.7219512195121951', 'ohc'],
       ['drive_wheels', '0.5853658536585366', 'fwd'],
       ['body_style', '0.4682926829268293', 'sedan'],
       ['fuel_system', '0.4585365853658537', 'mpfi'],
       ['make', '0.15609756097560976', 'toyota']], dtype='<U19')

In [95]:
selected[:, 2]

array(['ohc', 'fwd', 'sedan', 'mpfi', 'toyota'], dtype='<U19')

In [96]:
# detecting if the first character of the string in the "selected" array is digit or not.
def num_is_digit(array, str_index = 0):
    return np.array([value[str_index].isdigit() for value in array])

In [97]:
num_is_digit(selected[:, 2], str_index = 0)

array([False, False, False, False, False])

In [98]:
np.array(['ohc'[1]])

array(['h'], dtype='<U1')

In [99]:
def remove_digits_from_selected(selected_matrix, col_idx, str_indices = [0, -1]):
    for idx in str_indices:
        selected_col = selected_matrix[~num_is_digit(selected_matrix[:, col_idx], idx)]
    return selected_col

In [100]:
selected_sums_no_digits = remove_digits_from_selected(selected, 2, str_indices = [0, -1])
selected_sums_no_digits

array([['engine_type', '0.7219512195121951', 'ohc'],
       ['drive_wheels', '0.5853658536585366', 'fwd'],
       ['body_style', '0.4682926829268293', 'sedan'],
       ['fuel_system', '0.4585365853658537', 'mpfi'],
       ['make', '0.15609756097560976', 'toyota']], dtype='<U19')

In [101]:
# I modified the "find_categorical" method as below, using find_object_features(df) instead of df.columns to exclude numeric.

def find_categorical(df, threshold = .5):
    categorical_df = pd.DataFrame({})
    for column in find_object_features(df):
        if percentage_unique(df[column]) < threshold:
            categorical_df[column] = df[column]
    return categorical_df

In [102]:
find_categorical(df2).head(2)

          make   body_style drive_wheels engine_type fuel_system
0  alfa-romero  convertible          rwd        dohc        mpfi
1  alfa-romero  convertible          rwd        dohc        mpfi

In [103]:
finding_unique(df2, find_object_features(df2))

array(['make',
       array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object),
       'body_style',
       array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object),
       'drive_wheels', array(['rwd', 'fwd', '4wd'], dtype=object),
       'engine_type',
       array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object),
       'fuel_system',
       array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)], dtype=object)

In [104]:
len(df2['make'].unique()) == len(df2['make'].value_counts())

True

In [105]:
def categorical_plus_values(df, threshold = 2):
    categorical_cols = find_categorical(df)
    return [column for column in categorical_cols if len(df[column].unique()) > threshold]

In [106]:
updated_non_digits = categorical_plus_values(df2)
updated_non_digits

['make', 'body_style', 'drive_wheels', 'engine_type', 'fuel_system']

In [107]:
df2[updated_non_digits].describe()

          make body_style drive_wheels engine_type fuel_system
count      205        205          205         205         205
unique      22          5            3           7           8
top     toyota      sedan          fwd         ohc        mpfi
freq        32         96          120         148          94

In [108]:
def selected_cat_values(column, threshold = .05):
    values_counted = column.value_counts(normalize=True)
    return values_counted[values_counted > threshold]

In [109]:
selected = selected_cat_values(df1.make, .05).index
selected

Index(['toyota', 'nissan', 'mazda', 'mitsubishi', 'honda', 'volkswagen',
       'subaru', 'volvo', 'peugot'],
      dtype='object')

In [110]:
def reduce_cat_values(column, threshold = .05):
    column = column.copy()
    selected_values = selected_cat_values(column, threshold).index
    column[~column.isin(selected_values)] = 'other'
    column.astype('category', inplace=True)
    return column

In [111]:
def df_reduced_categories(df, categoricals, threshold = .05):
    new_df = pd.DataFrame()
    for category in categoricals:
        new_df[category] = reduce_cat_values(df[category], threshold)
    return new_df

In [112]:
df_reduced = df_reduced_categories(df2, updated_non_digits)

In [113]:
df_reduced.describe()

         make body_style drive_wheels engine_type fuel_system
count     205        205          205         205         205
unique     10          4            3           6           5
top     other      sedan          fwd         ohc        mpfi
freq       66         96          120         148          94

In [114]:
summarize_counts(df_reduced)

array([['engine_type', '0.7219512195121951', 'ohc'],
       ['drive_wheels', '0.5853658536585366', 'fwd'],
       ['body_style', '0.4682926829268293', 'sedan'],
       ['fuel_system', '0.4585365853658537', 'mpfi'],
       ['make', '0.32195121951219513', 'other']], dtype='<U32')

In [115]:
def replace_df_columns(original_df, replacing_df):
    replacing_cols = replacing_df.columns
    original_df = original_df.drop(columns = replacing_cols)
    new_df = pd.concat([original_df, replacing_df], axis = 1)
    return new_df

In [116]:
df3 = replace_df_columns(df2, df_reduced)

In [117]:
concat_datatype(df3)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,float64
num_of_doors,2,2,2,4,4,2,4,4,4,float64
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
num_of_cylinders,4,4,6,4,5,5,5,5,5,int64
engine_size,130,130,152,109,136,136,136,136,131,int64
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,float64
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,float64
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,float64
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64
engine_location_is_front,1,1,1,1,1,1,1,1,1,int32
fuel_type_is_gas,1,1,1,1,1,1,1,1,1,int32
aspiration_is_std,1,1,1,1,1,1,1,1,0,int32
make,other,other,other,other,other,other,other,other,other,object
body_style,other,other,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,other,fwd,fwd,fwd,fwd,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

In [118]:
len(df3['make'].unique())

10

In [119]:
len(df2['make'].unique())

22

In [120]:
df3['make'].unique()

array(['other', 'honda', 'mazda', 'mitsubishi', 'nissan', 'peugot',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [121]:
df3['make'].astype('category', inplace=True)

0      other
1      other
2      other
3      other
4      other
       ...
200    volvo
201    volvo
202    volvo
203    volvo
204    volvo
Name: make, Length: 205, dtype: category
Categories (10, object): [honda, mazda, mitsubishi, nissan, ..., subaru, toyota, volkswagen, volvo]

In [122]:
concat_datatype(df3)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,float64
num_of_doors,2,2,2,4,4,2,4,4,4,float64
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
num_of_cylinders,4,4,6,4,5,5,5,5,5,int64
engine_size,130,130,152,109,136,136,136,136,131,int64
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,float64
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,float64
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,float64
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64
engine_location_is_front,1,1,1,1,1,1,1,1,1,int32
fuel_type_is_gas,1,1,1,1,1,1,1,1,1,int32
aspiration_is_std,1,1,1,1,1,1,1,1,0,int32
make,other,other,other,other,other,other,other,other,other,object
body_style,other,other,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,other,fwd,fwd,fwd,fwd,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

In [123]:
df3.select_dtypes('object').astype('category', inplace=True).describe

<bound method NDFrame.describe of       make body_style drive_wheels engine_type fuel_system
0    other      other          rwd        dohc        mpfi
1    other      other          rwd        dohc        mpfi
2    other  hatchback          rwd        ohcv        mpfi
3    other      sedan          fwd         ohc        mpfi
4    other      sedan        other         ohc        mpfi
..     ...        ...          ...         ...         ...
200  volvo      sedan          rwd         ohc        mpfi
201  volvo      sedan          rwd         ohc        mpfi
202  volvo      sedan          rwd        ohcv        mpfi
203  volvo      sedan          rwd         ohc         idi
204  volvo      sedan          rwd         ohc        mpfi

[205 rows x 5 columns]>

In [124]:
df3['make'].astype('category').describe

<bound method NDFrame.describe of 0      other
1      other
2      other
3      other
4      other
       ...
200    volvo
201    volvo
202    volvo
203    volvo
204    volvo
Name: make, Length: 205, dtype: category
Categories (10, object): [honda, mazda, mitsubishi, nissan, ..., subaru, toyota, volkswagen, volvo]>

In [125]:
concat_datatype(df3)

,0,1,2,3,4,5,6,7,8,0
symboling,3,3,1,2,2,2,1,1,1,int64
normalized_losses,NaN,NaN,NaN,164,164,NaN,158,NaN,158,float64
num_of_doors,2,2,2,4,4,2,4,4,4,float64
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,float64
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,float64
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,float64
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,float64
curb_weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,int64
num_of_cylinders,4,4,6,4,5,5,5,5,5,int64
engine_size,130,130,152,109,136,136,136,136,131,int64
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,float64
compression_ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,float64
horsepower,111,111,154,102,115,110,110,110,140,float64
peak_rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,float64
city_mpg,21,21,19,24,18,19,19,19,17,int64
highway_mpg,27,27,26,30,22,25,25,25,20,int64
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,float64
engine_location_is_front,1,1,1,1,1,1,1,1,1,int32
fuel_type_is_gas,1,1,1,1,1,1,1,1,1,int32
aspiration_is_std,1,1,1,1,1,1,1,1,0,int32
make,other,other,other,other,other,other,other,other,other,object
body_style,other,other,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,object
drive_wheels,rwd,rwd,rwd,fwd,other,fwd,fwd,fwd,fwd,object
engine_type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,object
fuel_system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,object

### Now, I can get dummies for these five categorical features: 'make', 'body_style', 'drive_wheels', 'engine_type', 'fuel_system'.

In [126]:
updated_non_digits

['make', 'body_style', 'drive_wheels', 'engine_type', 'fuel_system']

In [127]:
df3.head(2).T

                              0      1
symboling                     3      3
normalized_losses           NaN    NaN
num_of_doors                  2      2
wheel-base                 88.6   88.6
length                    168.8  168.8
width                      64.1   64.1
height                     48.8   48.8
curb_weight                2548   2548
num_of_cylinders              4      4
engine_size                 130    130
bore                       3.47   3.47
stroke                     2.68   2.68
compression_ratio             9      9
horsepower                  111    111
peak_rpm                   5000   5000
city_mpg                     21     21
highway_mpg                  27     27
price                     13495  16500
engine_location_is_front      1      1
fuel_type_is_gas              1      1
aspiration_is_std             1      1
make                      other  other
body_style                other  other
drive_wheels                rwd    rwd
engine_type                dohc   dohc
fuel_system                mpfi   mpfi

### Getting dummy variables for "updated_non_digits" features.

In [128]:
import pandas as pd
df4 = pd.get_dummies(df3)
df4.T

,0,1,2,3,4,5,6,7,8,9,...,195,196,197,198,199,200,201,202,203,204
symboling,3.00,3.00,1.00,2.00,2.00,2.00,1.00,1.00,1.00,0.00,...,-1.00,-2.00,-1.00,-2.00,-1.00,-1.00,-1.00,-1.00,-1.00,-1.00
normalized_losses,NaN,NaN,NaN,164.00,164.00,NaN,158.00,NaN,158.00,NaN,...,74.00,103.00,74.00,103.00,74.00,95.00,95.00,95.00,95.00,95.00
num_of_doors,2.00,2.00,2.00,4.00,4.00,2.00,4.00,4.00,4.00,2.00,...,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00,4.00
wheel-base,88.60,88.60,94.50,99.80,99.40,99.80,105.80,105.80,105.80,99.50,...,104.30,104.30,104.30,104.30,104.30,109.10,109.10,109.10,109.10,109.10
length,168.80,168.80,171.20,176.60,176.60,177.30,192.70,192.70,192.70,178.20,...,188.80,188.80,188.80,188.80,188.80,188.80,188.80,188.80,188.80,188.80
width,64.10,64.10,65.50,66.20,66.40,66.30,71.40,71.40,71.40,67.90,...,67.20,67.20,67.20,67.20,67.20,68.90,68.80,68.90,68.90,68.90
height,48.80,48.80,52.40,54.30,54.30,53.10,55.70,55.70,55.90,52.00,...,57.50,56.20,57.50,56.20,57.50,55.50,55.50,55.50,55.50,55.50
curb_weight,2548.00,2548.00,2823.00,2337.00,2824.00,2507.00,2844.00,2954.00,3086.00,3053.00,...,3034.00,2935.00,3042.00,3045.00,3157.00,2952.00,3049.00,3012.00,3217.00,3062.00
num_of_cylinders,4.00,4.00,6.00,4.00,5.00,5.00,5.00,5.00,5.00,5.00,...,4.00,4.00,4.00,4.00,4.00,4.00,4.00,6.00,6.00,4.00
engine_size,130.00,130.00,152.00,109.00,136.00,136.00,136.00,136.00,131.00,131.00,...,141.00,141.00,141.00,130.00,130.00,141.00,141.00,173.00,145.00,141.00
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,3.13,...,3.78,3.78,3.78,3.62,3.62,3.78,3.78,3.58,3.01,3.78
stroke,2.68,2.68,3.47,3.40,3.40,3.40,3.40,3.40,3.40,3.40,...,3.15,3.15,3.15,3.15,3.15,3.15,3.15,2.87,3.40,3.15
compression_ratio,9.00,9.00,9.00,10.00,8.00,8.50,8.50,8.50,8.30,7.00,...,9.50,9.50,9.50,7.50,7.50,9.50,8.70,8.80,23.00,9.50
horsepower,111.00,111.00,154.00,102.00,115.00,110.00,110.00,110.00,140.00,160.00,...,114.00,114.00,114.00,162.00,162.00,114.00,160.00,134.00,106.00,114.00
peak_rpm,5000.00,5000.00,5000.00,5500.00,5500.00,5500.00,5500.00,5500.00,5500.00,5500.00,...,5400.00,5400.00,5400.00,5100.00,5100.00,5400.00,5300.00,5500.00,4800.00,5400.00
city_mpg,21.00,21.00,19.00,24.00,18.00,19.00,19.00,19.00,17.00,16.00,...,23.00,24.00,24.00,17.00,17.00,23.00,19.00,18.00,26.00,19.00
highway_mpg,27.00,27.00,26.00,30.00,22.00,25.00,25.00,25.00,20.00,22.00,...,28.00,28.00,28.00,22.00,22.00,28.00,25.00,23.00,27.00,25.00
price,13495.00,16500.00,16500.00,13950.00,17450.00,15250.00,17710.00,18920.00,23875.00,NaN,...,13415.00,15985.00,16515.00,18420.00,18950.00,16845.00,19045.00,21485.00,22470.00,22625.00
engine_location_is_front,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
fuel_type_is_gas,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,1.00
aspiration_is_std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00,...,1.00,1.00,1.00,0.00,0.00,1.00,0.00,1.00,0.00,0.00
make_honda,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_mazda,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_mitsubishi,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_nissan,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_other,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_peugot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_subaru,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_toyota,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_volkswagen,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
make_volvo,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
body_style_hatchback,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
body_style_other,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
body_style_sedan,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,1.00,0.00,...,0.00,1.00,0.00,1.00,0.00,1.00,1.00,1.00,1.00,1.00
body_style_wagon,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,...,1.00,0.00,1.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00
drive_wheels_fwd,0.00,0.00,0.00,1.00,0.00,1.00,1.00,1.00,1.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
drive_wheels_other,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,1.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
drive_wheels_rwd,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
engine_type_dohc,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
engine_type_l,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
engine_type_ohc,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,1.00,1.00
engine_type_ohcf,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
engine_type_ohcv,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00
engine_type_other,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
fuel_system_1bbl,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
fuel_system_2bbl,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
fuel_system_idi,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00
fuel_system_mpfi,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,1.00
fuel_system_other,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [129]:
df4.columns

Index(['symboling', 'normalized_losses', 'num_of_doors', 'wheel-base',
       'length', 'width', 'height', 'curb_weight', 'num_of_cylinders',
       'engine_size', 'bore', 'stroke', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price',
       'engine_location_is_front', 'fuel_type_is_gas', 'aspiration_is_std',
       'make_honda', 'make_mazda', 'make_mitsubishi', 'make_nissan',
       'make_other', 'make_peugot', 'make_subaru', 'make_toyota',
       'make_volkswagen', 'make_volvo', 'body_style_hatchback',
       'body_style_other', 'body_style_sedan', 'body_style_wagon',
       'drive_wheels_fwd', 'drive_wheels_other', 'drive_wheels_rwd',
       'engine_type_dohc', 'engine_type_l', 'engine_type_ohc',
       'engine_type_ohcf', 'engine_type_ohcv', 'engine_type_other',
       'fuel_system_1bbl', 'fuel_system_2bbl', 'fuel_system_idi',
       'fuel_system_mpfi', 'fuel_system_other'],
      dtype='object')

In [130]:
concat_datatype(df4)

,0,1,2,3,4,5,6,7,8,0
symboling,3.00,3.00,1.00,2.00,2.00,2.00,1.00,1.00,1.00,int64
normalized_losses,NaN,NaN,NaN,164.00,164.00,NaN,158.00,NaN,158.00,float64
num_of_doors,2.00,2.00,2.00,4.00,4.00,2.00,4.00,4.00,4.00,float64
wheel-base,88.60,88.60,94.50,99.80,99.40,99.80,105.80,105.80,105.80,float64
length,168.80,168.80,171.20,176.60,176.60,177.30,192.70,192.70,192.70,float64
width,64.10,64.10,65.50,66.20,66.40,66.30,71.40,71.40,71.40,float64
height,48.80,48.80,52.40,54.30,54.30,53.10,55.70,55.70,55.90,float64
curb_weight,2548.00,2548.00,2823.00,2337.00,2824.00,2507.00,2844.00,2954.00,3086.00,int64
num_of_cylinders,4.00,4.00,6.00,4.00,5.00,5.00,5.00,5.00,5.00,int64
engine_size,130.00,130.00,152.00,109.00,136.00,136.00,136.00,136.00,131.00,int64
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,float64
stroke,2.68,2.68,3.47,3.40,3.40,3.40,3.40,3.40,3.40,float64
compression_ratio,9.00,9.00,9.00,10.00,8.00,8.50,8.50,8.50,8.30,float64
horsepower,111.00,111.00,154.00,102.00,115.00,110.00,110.00,110.00,140.00,float64
peak_rpm,5000.00,5000.00,5000.00,5500.00,5500.00,5500.00,5500.00,5500.00,5500.00,float64
city_mpg,21.00,21.00,19.00,24.00,18.00,19.00,19.00,19.00,17.00,int64
highway_mpg,27.00,27.00,26.00,30.00,22.00,25.00,25.00,25.00,20.00,int64
price,13495.00,16500.00,16500.00,13950.00,17450.00,15250.00,17710.00,18920.00,23875.00,float64
engine_location_is_front,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,int32
fuel_type_is_gas,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,int32
aspiration_is_std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,int32
make_honda,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_mazda,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_mitsubishi,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_nissan,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_other,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,uint8
make_peugot,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_subaru,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_toyota,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_volkswagen,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
make_volvo,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
body_style_hatchback,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
body_style_other,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
body_style_sedan,0.00,0.00,0.00,1.00,1.00,1.00,1.00,0.00,1.00,uint8
body_style_wagon,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,uint8
drive_wheels_fwd,0.00,0.00,0.00,1.00,0.00,1.00,1.00,1.00,1.00,uint8
drive_wheels_other,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,uint8
drive_wheels_rwd,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
engine_type_dohc,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
engine_type_l,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
engine_type_ohc,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,uint8
engine_type_ohcf,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
engine_type_ohcv,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
engine_type_other,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
fuel_system_1bbl,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
fuel_system_2bbl,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
fuel_system_idi,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8
fuel_system_mpfi,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,uint8
fuel_system_other,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,uint8

In [131]:
df4.shape

(205, 49)

In [132]:
df4.head()

,symboling,normalized_losses,num_of_doors,wheel-base,length,width,height,curb_weight,num_of_cylinders,engine_size,...,engine_type_l,engine_type_ohc,engine_type_ohcf,engine_type_ohcv,engine_type_other,fuel_system_1bbl,fuel_system_2bbl,fuel_system_idi,fuel_system_mpfi,fuel_system_other
0,3,NaN,2.0,88.6,168.8,64.1,48.8,2548,4,130,...,0,0,0,0,0,0,0,0,1,0
1,3,NaN,2.0,88.6,168.8,64.1,48.8,2548,4,130,...,0,0,0,0,0,0,0,0,1,0
2,1,NaN,2.0,94.5,171.2,65.5,52.4,2823,6,152,...,0,0,0,1,0,0,0,0,1,0
3,2,164.0,4.0,99.8,176.6,66.2,54.3,2337,4,109,...,0,1,0,0,0,0,0,0,1,0
4,2,164.0,4.0,99.4,176.6,66.4,54.3,2824,5,136,...,0,1,0,0,0,0,0,0,1,0

In [133]:
df4.columns

Index(['symboling', 'normalized_losses', 'num_of_doors', 'wheel-base',
       'length', 'width', 'height', 'curb_weight', 'num_of_cylinders',
       'engine_size', 'bore', 'stroke', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price',
       'engine_location_is_front', 'fuel_type_is_gas', 'aspiration_is_std',
       'make_honda', 'make_mazda', 'make_mitsubishi', 'make_nissan',
       'make_other', 'make_peugot', 'make_subaru', 'make_toyota',
       'make_volkswagen', 'make_volvo', 'body_style_hatchback',
       'body_style_other', 'body_style_sedan', 'body_style_wagon',
       'drive_wheels_fwd', 'drive_wheels_other', 'drive_wheels_rwd',
       'engine_type_dohc', 'engine_type_l', 'engine_type_ohc',
       'engine_type_ohcf', 'engine_type_ohcv', 'engine_type_other',
       'fuel_system_1bbl', 'fuel_system_2bbl', 'fuel_system_idi',
       'fuel_system_mpfi', 'fuel_system_other'],
      dtype='object')

### To make the next steps easy, I will change the orders of columnsin the dataframe, to place the target variable in the last column as below.

In [134]:
df4 = df4[['symboling', 'num_of_doors', 'wheel-base',
       'length', 'width', 'height', 'curb_weight', 'num_of_cylinders',
       'engine_size', 'bore', 'stroke', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price',
       'engine_location_is_front', 'fuel_type_is_gas', 'aspiration_is_std',
       'make_honda', 'make_mazda', 'make_mitsubishi', 'make_nissan',
       'make_other', 'make_peugot', 'make_subaru', 'make_toyota',
       'make_volkswagen', 'make_volvo', 'body_style_hatchback',
       'body_style_other', 'body_style_sedan', 'body_style_wagon',
       'drive_wheels_fwd', 'drive_wheels_other', 'drive_wheels_rwd',
       'engine_type_dohc', 'engine_type_l', 'engine_type_ohc',
       'engine_type_ohcf', 'engine_type_ohcv', 'engine_type_other',
       'fuel_system_1bbl', 'fuel_system_2bbl', 'fuel_system_idi',
       'fuel_system_mpfi', 'fuel_system_other', 'normalized_losses']]

In [135]:
df4.head()

,symboling,num_of_doors,wheel-base,length,width,height,curb_weight,num_of_cylinders,engine_size,bore,...,engine_type_ohc,engine_type_ohcf,engine_type_ohcv,engine_type_other,fuel_system_1bbl,fuel_system_2bbl,fuel_system_idi,fuel_system_mpfi,fuel_system_other,normalized_losses
0,3,2.0,88.6,168.8,64.1,48.8,2548,4,130,3.47,...,0,0,0,0,0,0,0,1,0,NaN
1,3,2.0,88.6,168.8,64.1,48.8,2548,4,130,3.47,...,0,0,0,0,0,0,0,1,0,NaN
2,1,2.0,94.5,171.2,65.5,52.4,2823,6,152,2.68,...,0,0,1,0,0,0,0,1,0,NaN
3,2,4.0,99.8,176.6,66.2,54.3,2337,4,109,3.19,...,1,0,0,0,0,0,0,1,0,164.0
4,2,4.0,99.4,176.6,66.4,54.3,2824,5,136,3.19,...,1,0,0,0,0,0,0,1,0,164.0

### Now, I completed feature engineering to convert every feature into numeric datatype by using respective engineering methods as shown above. I will go to the next step: scaling the features into z-score and then feature selection.

In [136]:
#exporting the dataframe with engineered features as csv file for later use.
df4.to_csv(r'C:\Users\Minyeong\Desktop\engineered_features.csv')

### Resources

[detecting missing values](https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba)

[detecting outliers](https://machinelearningmastery.com/how-to-use-statistics-to-identify-outliers-in-data/)